{{ if .Values.infinispan.jgroupsTls }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-jgroups-pkcs12-password
  namespace: {{ .Values.namespace }}
data:
  password: a2V5Y2xvYWs= # keycloak
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-jgroups-selfsigned
  namespace: {{ .Values.namespace }}
spec:
  # This certificate will be valid for 90 days by default, with a renewal after 60 days.
  # In a production environment, consider using a longer duration, as after each renewal, the Keycloak pods would need to be restarted
  commonName: keycloak-jgroups
  secretName: keycloak-jgroups
  keystores:
    pkcs12:
      create: true
      passwordSecretRef: # Password used to encrypt the keystore
        key: password
        name: keycloak-jgroups-pkcs12-password
  issuerRef:
    name: selfsigned
    kind: Issuer
    group: cert-manager.io
{{ end }}
