= ROSA Deployment

Deploy Infinispan, Keycloak and Aurora Database between 2 different ROSA clusters.

== Taskfile

Run `go-task --list` for the available tasks:

[source]
----
task: Available tasks for this project:
* default:        Deploys Infinispan, Aurora DB and Keycloak in a Cross-Site deployment using ROSA clusters
* undeploy:       Undeploy Infinispan and Keycloak in a Cross-Site deployment using ROSA clusters
----

NOTE: Aurora DB and peer connection need to be manually cleaned after the testing.

=== Required variables

|===
|Variable |Details

|AURORA_CLUSTER
|The unique name for Aurora Database. The database is created if it does not exist.

|AURORA_REGION
|The region to deploy Aurora DB.

|ROSA_CLUSTER_NAME_1
|The mame of one ROSA cluster.

|ROSA_CLUSTER_NAME_2
|The mame of the other ROSA cluster.
|===

=== Other variables

All variables declared in `openshift/`, `infinispan/` task files can be used to tune the deployment.

=== Warnings / Known issues

Using `--force` will break the keycloak deployment because it patches the keycloak operator deployment with an incorrect image.

