{{ if or (eq .Values.database "infinispan") (eq .Values.database "postgres+infinispan") }}
apiVersion: v1
kind: Service
metadata:
  name: infinispan-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: infinispan
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 11222
      nodePort: {{ add 30011 (mul .Values.portOffset 100) }}
  selector:
    app: infinispan
{{ end }}
