{{ if or (eq .Values.database "infinispan") (eq .Values.database "mixed") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: infinispan
  name: infinispan
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 11222
      name: console
      protocol: TCP
      targetPort: 11222
  selector:
    app: infinispan
  sessionAffinity: None
  type: ClusterIP
{{ end }}
