{{ if or (eq .Values.database "infinispan") (eq .Values.database "mixed") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infinispan
  name: infinispan
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: infinispan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: infinispan
    spec:
      containers:
        - image: quay.io/infinispan/server:14.0.4.Final
          env:
            - name: USER
              value: admin
            - name: PASS
              value: admin
          imagePullPolicy: Always
          startupProbe:
            tcpSocket:
              port: 11222
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 2
          readinessProbe:
            tcpSocket:
              port: 11222
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 11222
            failureThreshold: 10
            periodSeconds: 10
          name: infinispan
          ports:
            - containerPort: 11222
              protocol: TCP
      restartPolicy: Always
{{ end }}
