{{ if or (eq .Values.database "infinispan") (eq .Values.database "mixed") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: infinispan
  name: infinispan
  namespace: keycloak
spec:
  defaultBackend:
    service:
      name: infinispan
      port:
        number: 11222
  rules:
    - host: infinispan.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: infinispan
                port:
                  number: 11222
            path: /
            pathType: ImplementationSpecific
{{end}}
