{{ if .Values.infinispan.remoteStore.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: remote-store-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.infinispan.remoteStore.username | b64enc }}
  password: {{ .Values.infinispan.remoteStore.password | b64enc }}
{{ end }}
