{{ if .Values.infinispan.remoteStore.enabled }}
# tag::keycloak-ispn-secret[]
apiVersion: v1
kind: Secret
metadata:
  name: remote-store-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.infinispan.remoteStore.username | b64enc }} # base64 encoding for '{{ .Values.infinispan.remoteStore.username }}'
  password: {{ .Values.infinispan.remoteStore.password | b64enc }} # base64 encoding for '{{ .Values.infinispan.remoteStore.password }}'
# end::keycloak-ispn-secret[]
{{ end }}
