{{- if .Values.customImage }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: keycloak-operator
  namespace: {{ .Values.namespace }}
  labels:
    build: keycloak-operator
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: keycloak-operator
  name: keycloak-operator
  namespace: {{ .Values.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: keycloak-operator:latest
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: ubi9:latest
    type: Docker
  {{ end }}
