{{- if and (.Values.useAWSJDBCWrapper) (not .Values.customImage) }}
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/keycloak/keycloak:nightly
      generation: 2
      importPolicy:
        importMode: PreserveOriginal
      referencePolicy:
        type: Source
{{ end }}
