{{ if eq .Values.database "cockroach-single" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cockroach
  name: cockroach
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 26257
      name: database
      protocol: TCP
      targetPort: 26257
    - port: 8080
      name: console
      protocol: TCP
      targetPort: 8080
  selector:
    app: cockroach
  sessionAffinity: None
  type: ClusterIP
{{ end }}
