{{ if and (eq .Values.database "cockroach-single") (.Values.nodePortsEnabled) }}
apiVersion: v1
kind: Service
metadata:
  name: cockroach-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: cockroach
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 26257
      nodePort: {{ add 30010 (mul .Values.portOffset 100) }}
  selector:
    app: cockroach
{{ end }}
