{{ if eq .Values.database "cockroach-single" }}
{{ if .Values.monitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cockroach
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "config/cockroach-initdb-insecure.sql").AsConfig | indent 2 }}
{{ end }}
{{ end }}
