name: Create Keycloak Deployment
description: Create Keycloak Deployment for running OpenShift project

inputs:
  projectPrefix:
    description: 'Prefix of the project'
    required: true
  replicas:
    description: 'Number of keycloak pods'
    required: true
    default: '3'
  disableStickySessions:
    description: 'Disable sticky session in OpenShift Route'
    default: 'true'
  image:
    description: 'Keycloak Image'
  podMemoryRequests:
    description: 'Keycloak pod memory requests (in MB)'
  podMemoryLimit:
    description: 'Keycloak pod memory limit (in MB)'
  podCpuRequests:
    description: 'Keycloak pod CPU requests'
  podCpuLimit:
    description: 'Keycloak pod CPU limit'
  otel:
    description: 'Enable OpenTelemetry'
    default: 'false'
  database:
    description: 'The Database type to be utilised by Keycloak'
    default: 'postgres'
  databaseUrl:
    description: 'The external URL of the database'
  kcHostnameOverride:
    description: 'The hostname to be used by Keycloak'
  kcHealthHostname:
    description: 'The hostname used to create a health Route'

runs:
  using: "composite"
  steps:
    - id: setup_go_task
      uses: ./.github/actions/task-setup

    - id: install_keycloak
      shell: bash
      run: task
      working-directory: provision/openshift
      env:
        KC_NAMESPACE_PREFIX: ${{ inputs.projectPrefix }}
        KC_INSTANCES: ${{ inputs.replicas }}
        KC_DISABLE_STICKY_SESSION: ${{ inputs.disableStickySessions }}
        KC_CONTAINER_IMAGE: ${{ inputs.image }}
        KC_MEMORY_REQUESTS_MB: ${{ inputs.podMemoryRequests }}
        KC_MEMORY_LIMITS_MB: ${{ inputs.podMemoryLimit }}
        KC_CPU_REQUESTS: ${{ inputs.podCpuRequests }}
        KC_CPU_LIMITS: ${{ inputs.podCpuLimit }}
        KC_OTEL: ${{ inputs.otel }}
        KC_DATABASE: ${{ inputs.database }}
        KC_DATABASE_URL: ${{ inputs.databaseUrl }}
        KC_HOSTNAME_OVERRIDE: ${{ inputs.kcHostnameOverride }}
        KC_HEALTH_HOSTNAME: ${{ inputs.kcHealthHostname }}
