{{ if eq .Values.database "cockroach-operator" }}
apiVersion: v1
kind: Service
metadata:
  name: cockroach-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: cockroach
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 26257
      nodePort: 30013
  selector:
    app.kubernetes.io/instance: cockroach
    app.kubernetes.io/name: cockroachdb
{{ end }}
