{{ if eq .Values.database "cockroach-operator" }}

apiVersion: v1
kind: Service
metadata:
  name: cockroach-client-secure
  labels:
    app: cockroach-client-secure
spec:
  clusterIP: None
  selector:
    app: cockroach-client-secure
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cockroach-client-secure
  namespace: {{ .Values.namespace }}
spec:
  serviceName: cockroach-client-secure
  selector:
    matchLabels:
      app: cockroach-client-secure
  template:
    metadata:
      labels:
        app: cockroach-client-secure
    spec:
      serviceAccountName: cockroach-sa
      containers:
        - name: cockroach-client-secure
          image: cockroachdb/cockroach:v22.1.8
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach/cockroach-certs/
          command:
            #  ./cockroach sql --certs-dir=/cockroach/cockroach-certs --host=cockroach-public
            - sleep
            - "2147483648" # 2^31
      terminationGracePeriodSeconds: 0
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: cockroach-node
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: cockroach-root
                  items:
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256

{{ end }}
