{{ if eq .Values.database "cockroach-operator" }}
{{ if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cockroach-metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: cockroach
      app.kubernetes.io/name: cockroachdb
  podMetricsEndpoints:
    # todo: targetPort is deprecated, ask the operator to specify a name instead
    - targetPort: 8080
      path: /_status/vars
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{ end }}
{{ end }}
