{{ if eq .Values.database "cockroach-operator" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: cockroach
  name: cockroach
  namespace: keycloak
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  defaultBackend:
    service:
      name: cockroach
      port:
        number: 8080
  rules:
    - host: cockroach.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: cockroach
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
{{end}}
