{{ if eq .Values.database "cockroach-operator" }}

apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  # this translates to the name of the statefulset that is created
  name: cockroach
  namespace: {{ .Values.namespace }}
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "20Gi"
        volumeMode: Filesystem
  tlsEnabled: true
  # You can set either a version of the db or a specific image name
  # cockroachDBVersion: v22.1.8
  image:
    name: cockroachdb/cockroach:v22.1.8
  # nodes refers to the number of crdb pods that are created
  # via the statefulset
  nodes: 3

{{ end }}
