name: Delete EC2 instances
description: Deletes EC2 instances

inputs:
  region:
    description: 'The AWS region used to delete the EC2 instances.'
    required: true

runs:
  using: composite
  steps:
    - id: delete-load-runners
      shell: bash
      run: |
        source .venv/bin/activate
        ./aws_ec2.sh delete ${{ inputs.region }}
      working-directory: ansible
