= Infinispan Installer

Deploy an Infinispan cluster (with or without cross-site) and configures the necessary caches for Keycloak.

== Taskfile

For single cluster mode:

[source, bash]
----
task single-cluster ROSA_CLUSTER_NAME=gh-keycloak OC_NAMESPACE=infinispan
----

For cross-site between different namespaces:

[source, bash]
----
task crossdc-single ROSA_CLUSTER_NAME=gh-keycloak OC_NAMESPACE_1=ispn-1 OC_NAMESPACE_2=ispn-2
----

And finally, for cross-site between different OCP clusters:
[source, bash]
----
task crossdc ROSA_CLUSTER_NAME_1=gh-keycloak ROSA_CLUSTER_NAME_2=gh-pruivo OC_NAMESPACE_1=infinispan OC_NAMESPACE_2=infinispan
----

== Provision Keycloak

The Taskfile in `provistion/openshift` introduced 4 more variables:


|===
|Variable |Default |Details

|`KC_CUSTOM_INFINISPAN_CONFIG_FILE`
|`config/kcb-infinispan-cache-config.xml`
|The path to the Infinispan configuration file to be used by Keycloak

|`KC_ISPN_NAMESPACE`
|-
|The namespace where the Infinispan cluster is installed.
|===

As an example, using a single Infinispan cluster, Infinispan and keycloak can be deployed using the
following commands from this directory (assuming `.env` is properly configured to access the OCP cluster):

[source, bash]
----
cd provistion/infinispan
task single-cluster ROSA_CLUSTER_NAME=gh-keycloak OC_NAMESPACE=ispn-server
cd ../provistion/openshift
task KC_CUSTOM_INFINISPAN_CONFIG_FILE=config/kcb-infinispan-cache-remote-store-config.xml KC_ISPN_NAMESPACE=ispn-server
----
