# https://taskfile.dev
version: '3'
includes:
  utils:
    taskfile: ./Utils.yaml
    internal: true
output: prefixed

dotenv: [ '.env' ]

tasks:
  wait-cluster:
    desc: "Waits for the Infinispan cluster to form"
    cmd:
      task: utils:{{.TASK}}

  wait-crossdc:
    desc: "Waits for the Infinispan Cross-Site to form"
    cmd:
      task: utils:{{.TASK}}

  single-cluster:
    desc: "Creates a single cluster Infinispan deployment"
    cmd:
      task: utils:{{.TASK}}

  crossdc-single:
    desc: "Creates a cross-site enabled Infinispan deployment between 2 namespaces"
    cmd:
      task: utils:{{.TASK}}

  crossdc:
    desc: "Creates a cross-site enabled Infinispan deployment between 2 OCP clusters"
    cmd:
      task: utils:{{.TASK}}

  crossdc-connect:
    desc: "Bring the backup site online"
    cmd:
      task: utils:{{.TASK}}

  crossdc-disconnect:
    desc: "Take the backup site offline"
    cmd:
      task: utils:{{.TASK}}

  delete-infinispan:
    desc: "Deletes the Infinispan CR"
    cmd:
      task: utils:{{.TASK}}

  delete-crossdc-single:
    desc: "Deletes the Infinispan CR in a cross-site deployment in a single OCP cluster"
    cmd:
      task: utils:{{.TASK}}

  delete-crossdc:
    desc: "Deletes the Infinispan CR from cross-site deployment"
    cmd:
      task: utils:{{.TASK}}

  crossdc-split:
    desc: "Simulate a split-brain by taking down the GossipRouter on each site"
    cmd:
      task: utils:{{.TASK}}

  crossdc-heal:
    desc: "Heal a simulated split-brain by recreating down the GossipRouter on each site"
    cmd:
      task: utils:{{.TASK}}

  crossdc-sync-state:
    desc: "Synchronize the cache state of ROSA_CLUSTER_NAME_2 with ROSA_CLUSTER_NAME_1"
    cmd:
      task: utils:{{.TASK}}
