name: Restart Keycloak Pods
description: Restart Keycloak Pods and wait

inputs:
  project:
    description: OpenShift project where Keycloak is running
    required: true
  keycloak_operator_name:
    type: string
    default: keycloak-operator
    
runs:
  using: "composite"
  steps:
    - id: restart-keycloak-pods
      shell: bash
      working-directory: benchmark/src/main/content/bin
      run: ./kc-rolling-restart.sh
      env:
        POD_LABEL: "keycloak"
        KC_OPERATOR_NAME: ${{ inputs.keycloak_operator_name }}