apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-jvmdebug
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  ports:
    - name: jvmdebug
      port: 8787
      protocol: TCP
      nodePort: {{ add 30012 (mul .Values.portOffset 100) }}
  selector:
    app: keycloak
  sessionAffinity: None
