# There are several callouts in this YAML marked with `# <1>' etc. See 'running/keycloak-deployment.adoc` for the details.
# tag::keycloak[]
# tag::keycloak-ispn[]
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
# end::keycloak-ispn[]
  hostname:
    {{- if .Values.keycloakHostname }}
    hostname: {{ .Values.keycloakHostname }}
    {{- else }}
    hostname: keycloak-{{ .Values.namespace }}.{{ .Values.hostname }}
    {{- end }}
  resources:
    requests:
      {{ if .Values.cpuRequests }}cpu: "{{ .Values.cpuRequests }}"{{end}}
      {{ if .Values.memoryRequestsMB }}memory: "{{ .Values.memoryRequestsMB }}M"{{end}}
    limits:
      {{ if .Values.cpuLimits }}cpu: "{{ .Values.cpuLimits }}"{{end}}
      {{ if .Values.memoryLimitsMB }}memory: "{{ .Values.memoryLimitsMB }}M"{{end}}
  db:
{{ if or (eq .Values.database "aurora-postgres") (eq .Values.database "postgres") (eq .Values.database "postgres+infinispan") }}
    vendor: postgres
{{- if .Values.useAWSJDBCWrapper}}
    url: jdbc:aws-wrapper:postgresql://{{ .Values.dbUrl }}:5432/keycloak
{{- else }}
    url: jdbc:postgresql://postgres:5432/keycloak
{{ end }}
{{ end }}
    poolMinSize: {{ .Values.dbPoolMinSize }} # <1>
    poolInitialSize: {{ .Values.dbPoolInitialSize }}
    poolMaxSize: {{ .Values.dbPoolMaxSize }}
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
{{ if .Values.disableIngressStickySession }}
  ingress:
    enabled: true
    annotations:
      # When running load tests, disable sticky sessions on the OpenShift HAProxy router
      # to avoid receiving all requests on a single Keycloak Pod.
      haproxy.router.openshift.io/balance: roundrobin
      haproxy.router.openshift.io/disable_cookies: 'true'
{{end}}
{{ if .Values.keycloakImage }}
  image: {{ .Values.keycloakImage }} # <2>
  startOptimized: {{ .Values.startOptimized }} # <2>
{{ end }}
  features:
    enabled:
{{- if .Values.multiSite }}
      - multi-site # <3>
{{- end }}
{{- if .Values.externalInfinispan }}
      - remote-cache
{{- end }}
{{- if .Values.infinispan.customConfig }}
  # tag::keycloak-ispn[]
  cache:
    configMapFile:
        name: kcb-infinispan-cache-config # <1>
        key: {{ base .Values.infinispan.configFile }} # <1>
  # end::keycloak-ispn[]
{{- end }}
{{- if .Values.useAWSJDBCWrapper }}
  transaction:
    xaEnabled: false # <4>
{{ end }}
  # tag::keycloak-ispn[]
  additionalOptions:
  # end::keycloak-ispn[]
    {{ if .Values.otel }}
    - name: tracing-enabled
      value: "true"
    - name: tracing-endpoint
      value: "http://jaeger-collector.monitoring.svc:4317"
    - name: tracing-sampler-ratio
      value: {{ .Values.otelSamplingPercentage | quote }}
    - name: tracing-sampler-type
      value: "parentbased_traceidratio"
    {{- end }}
    {{- if .Values.persistentSessions }}
    - name: spi-user-sessions-infinispan-use-caches
      value: "false"
    {{- end }}
    - name: http-metrics-histograms-enabled
      value: 'true'
    - name: http-metrics-slos
      value: '5,10,25,50,250,500'
{{- if or (eq .Values.database "infinispan") (eq .Values.database "postgres+infinispan") }}
    - name: storage-hotrod-host
      value: infinispan
    - name: storage-hotrod-port
      value: '11222'
    - name: storage-hotrod-username
      value: admin
    - name: storage-hotrod-password
      value: admin
{{ end }}
{{- if .Values.disableCaches }}
    - name: cache-realm-enabled
      value: 'false'
    - name: cache-user-enabled
      value: 'false'
    - name: cache-authorization-enabled
      value: 'false'
    - name: spi-public-key-cache-infinispan-enabled
      value: 'false'
{{ end }}
    # tag::keycloak-queue-size[]
    - name: http-max-queued-requests
      value: "1000"
    # end::keycloak-queue-size[]
    - name: log-console-output
      value: json
    - name: metrics-enabled # <5>
      value: 'true'
    - name: http-pool-max-threads # <6>
      value: {{ div 200 .Values.instances | quote }}
{{- if .Values.infinispan.remoteStore.enabled }}
    # tag::keycloak-ispn[]
    - name: cache-remote-host # <1>
      value: {{ quote .Values.infinispan.remoteStore.host }}
    - name: cache-remote-port # <2>
      value: {{ quote .Values.infinispan.remoteStore.port }}
    - name: cache-remote-username # <3>
      secret:
        name: remote-store-secret
        key: username
    - name: cache-remote-password # <4>
      secret:
        name: remote-store-secret
        key: password
    {{- if .Values.infinispan.site }}
    - name: spi-connections-infinispan-quarkus-site-name # <5>
      value: {{ .Values.infinispan.site }}
    {{ end }}
    # end::keycloak-ispn[]
{{- end }}
{{- if .Values.infinispan.jgroupsTls }}
    - name: cache-embedded-mtls-enabled
      value: "true"
    - name: cache-embedded-mtls-key-store-file
      value: /etc/cache-embedded-mtls/keystore.p12
    - name: cache-embedded-mtls-key-store-password
      secret:
        name: keycloak-jgroups-pkcs12-password
        key: password
    - name: cache-embedded-mtls-trust-store-file
      value: /etc/cache-embedded-mtls/truststore.p12
    - name: cache-embedded-mtls-trust-store-password
      secret:
        name: keycloak-jgroups-pkcs12-password
        key: password
{{- end }}
{{ if .Values.useAWSJDBCWrapper }}
    - name: db-driver
      value: software.amazon.jdbc.Driver
{{ end }}
  http:
    tlsSecret: keycloak-tls-secret
  instances: {{ .Values.instances }}
  # end::keycloak[]
  unsupported:
    podTemplate:
      metadata:
        annotations:
          checksum/config: {{ include (print $.Template.BasePath "/keycloak-providers-configmap.yaml") . | sha256sum }}-{{ include (print $.Template.BasePath "/postgres/postgres-deployment.yaml") . | sha256sum }}-{{ .Values.keycloakImage }}-{{ include (print $.Template.BasePath "/keycloak-infinispan-configmap.yaml") . | sha256sum }}
      spec:
        containers:
          -
{{ if hasPrefix "localhost/" .Values.keycloakImage }}
            imagePullPolicy: Never
{{ end }}
            env:
              # We want to have an externally provided username and password, therefore, we override those two environment variables
              - name: KC_BOOTSTRAP_ADMIN_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: keycloak-preconfigured-admin
                    key: username
                    optional: false
              - name: KC_BOOTSTRAP_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-preconfigured-admin
                    key: password
                    optional: false
              - name: JAVA_OPTS_APPEND # <5>
                value: >
{{- if not (eq (int .Values.metaspaceInitMB) 96) }}
                  -XX:MetaspaceSize={{ .Values.metaspaceInitMB }}m
{{- end }}
{{- if not (eq (int .Values.metaspaceMaxMB) 256) }}
                  -XX:MaxMetaspaceSize={{ .Values.metaspaceMaxMB }}m
{{- end }}
{{- if .Values.jvmDebug }}
                  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
{{- end }}
{{- if .Values.cryostat }}
{{- end }}
            ports:
{{ if .Values.cryostat }}
              - containerPort: 9091
                protocol: TCP
                name: jfr-jmx
{{ end }}
{{ if .Values.jvmDebug }}
              - containerPort: 8787
                protocol: TCP
                name: jvm-debug
{{ end }}
            # end::keycloak[]
            # readinessProbe:
            #   exec:
            #     command:
            #       - 'true'
            # livenessProbe:
            #   exec:
            #     command:
            #       - 'true'
            volumeMounts:
              {{- range $path, $size := .Files.Glob "providers/**" }}
              {{- $name := base $path }}
              - name: keycloak-providers
                mountPath: /opt/keycloak/providers/{{ $name }}
                subPath: {{ $name }}
                readOnly: true
              {{- end -}}
{{ if .Values.infinispan.jgroupsTls }}
              - name: cache-embedded-mtls-volume
                mountPath: /etc/cache-embedded-mtls
                readOnly: true
{{ end }}
        volumes:
          - name: keycloak-providers
            configMap:
              name: keycloak-providers
{{ if .Values.infinispan.jgroupsTls }}
          - name: cache-embedded-mtls-volume
            secret:
              secretName: keycloak-jgroups
{{ end }}
