apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  hostname: keycloak.{{ .Values.hostname }}
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url
      value: jdbc:postgresql://postgres:5432/keycloak
    - name: log-console-output
      value: json
    - name: metrics-enabled
      value: 'true'
    - name: health-enabled
      value: 'true'
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password
  tlsSecret: keycloak-tls-secret
  instances: 1
  unsupported:
    podTemplate:
      spec:
        containers:
          -
{{ if .Values.otel }}
            command:
              - /bin/bash
            args:
              - -c
              - curl -L https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.15.0/opentelemetry-javaagent.jar -o /tmp/opentelemetry-javaagent.jar && /opt/keycloak/bin/kc.sh start --auto-build
{{ end }}
            env:
{{ if .Values.otel }}
              - name: JAVA_OPTS_APPEND
                # using non-blocking random, make DNS lookups expire after 10 seconds and not cache them forever
                value: -Djava.security.egd=file:/dev/urandom -Dnetworkaddress.cache.ttl=10 -javaagent:/tmp/opentelemetry-javaagent.jar -XX:+ExitOnOutOfMemoryError
              # https://github.com/open-telemetry/opentelemetry-java-instrumentation
              # https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
              - name: OTEL_RESOURCE_ATTRIBUTES
                value: service.name=keycloak
              - name: OTEL_TRACES_EXPORTER
                # with otel+tempo 1.4.1 forwarding of traces works, but searching is not returning all values for now, for example delete users was missing
                value: jaeger
              - name: OTEL_EXPORTER_JAEGER_ENDPOINT
                value: http://jaeger-collector.monitoring.svc:14250
              - name: OTEL_TRACES_SAMPLER
                value: always_on
              - name: OTEL_METRICS_EXPORTER
                value: prometheus
{{ else }}
              - name: JAVA_OPTS_APPEND
                # using non-blocking random, make DNS lookups expire after 10 seconds and not cache them forever
                value: -Djava.security.egd=file:/dev/urandom -Dnetworkaddress.cache.ttl=10 -XX:+ExitOnOutOfMemoryError
{{ end }}
{{ if .Values.otel }}
            ports:
              - containerPort: 9464
                protocol: TCP
                name: otel-prometheus
{{ end }}
            resources: {}
              # limits:
              #  cpu: "2000m"
              #  memory: "1500Mi"
            startupProbe:
              httpGet:
                path: /health/ready
                port: 8443
                scheme: HTTPS
              failureThreshold: 250
              initialDelaySeconds: 10
              periodSeconds: 2
            readinessProbe:
              httpGet:
                path: /health/ready
                port: 8443
                scheme: HTTPS
              failureThreshold: 10
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health/live
                port: 8443
                scheme: HTTPS
              failureThreshold: 10
              periodSeconds: 10

