{{ if .Values.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  # Use pod target labels "as is" without any renaming
  # podTargetLabels:
  #   - app
  # Since at least Keycloak 26.2 and the latest Quarkus 3.19 version, it requires "OpenMetricsText1.0.0" to retrieve exemplars,
  # as at least some of the other protocols don't support exemplars.
  scrapeProtocols:
    - OpenMetricsText1.0.0
  podMetricsEndpoints:
    - port: management
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - targetLabel: application
          # Alternative: hard-coded value
          # replacement: "keycloak"
          sourceLabels:
          - __meta_kubernetes_pod_label_app
          regex: (.+)
          replacement: ${1}

{{ end }}
