apiVersion: v1
kind: Secret
metadata:
  labels:
    app: keycloak
  name: keycloak-initial-admin
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
data:
  password: YWRtaW4= # admin
  username: YWRtaW4= # admin
