{{ if .Values.otel }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryostat
  name: otel
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  {{ if eq .Values.environment "openshift" }}
  storageClassName: efs-sc
  {{ else }}
  storageClassName: standard
  {{ end }}
  volumeMode: Filesystem
{{end}}
