{{ if or (eq .Values.database "postgres") (eq .Values.database "cockroach-single") (eq .Values.database "cockroach-operator") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlpad
  name: sqlpad
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sqlpad
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlpad
    spec:
      containers:
        - env:
            - name: SQLPAD_ADMIN
              value: 'admin'
            - name: SQLPAD_ADMIN_PASSWORD
              value: 'admin'
            - name: SQLPAD_PORT
              value: '3000'
            - name: SQLPAD_APP_LOG_LEVEL
              value: debug
            - name: SQLPAD_WEB_LOG_LEVEL
              value: warn
            - name: SQLPAD_SEED_DATA_PATH
              value: /etc/sqlpad/seed-data
{{ if eq .Values.database "postgres" }}
            - name: SQLPAD_CONNECTIONS__pgdemo__name
              value: PostgresSQL Keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__port
              value: '5432'
            - name: SQLPAD_CONNECTIONS__pgdemo__host
              value: postgres
            - name: SQLPAD_CONNECTIONS__pgdemo__username
              value: keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__password
              value: pass
{{ end }}
{{ if eq .Values.database "cockroach-single" }}
            - name: SQLPAD_CONNECTIONS__pgdemo__name
              value: CockroachDB Single Keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__port
              value: '26257'
            - name: SQLPAD_CONNECTIONS__pgdemo__host
              value: cockroach
            - name: SQLPAD_CONNECTIONS__pgdemo__username
              value: keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__password
              value: pass
{{ end }}
{{ if eq .Values.database "cockroach-operator" }}
            - name: SQLPAD_CONNECTIONS__pgdemo__name
              value: CockroachDB Operator Keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__port
              value: '26257'
            - name: SQLPAD_CONNECTIONS__pgdemo__host
              value: cockroach-public
            - name: SQLPAD_CONNECTIONS__pgdemo__username
              value: root
            - name: SQLPAD_CONNECTIONS__pgdemo__postgresSsl
              value: 'true'
            - name: SQLPAD_CONNECTIONS__pgdemo__postgresCert
              value: '/cockroach/cockroach-certs/client.root.crt'
            - name: SQLPAD_CONNECTIONS__pgdemo__postgresKey
              value: '/cockroach/cockroach-certs/client.root.key'
            - name: SQLPAD_CONNECTIONS__pgdemo__postgresCA
              value: '/cockroach/cockroach-certs/ca.crt'
{{ end }}
            - name: SQLPAD_CONNECTIONS__pgdemo__database
              value: keycloak
            - name: SQLPAD_CONNECTIONS__pgdemo__driver
              value: postgres
            - name: SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled
              value: 'true'
            - name: SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds
              value: '86400'
            - name: SQLPAD_QUERY_RESULT_MAX_ROWS
              value: '100000'
          image: sqlpad/sqlpad:6.11.0
          imagePullPolicy: Always
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 10
            periodSeconds: 10
          name: sqlpad
          ports:
            - containerPort: 3000
              protocol: TCP
{{ if eq .Values.database "cockroach-operator" }}
          volumeMounts:
            - name: client-certs
              mountPath: /cockroach/cockroach-certs/
      volumes:
        - name: client-certs
          projected:
            sources:
              - secret:
                  name: cockroach-node
                  items:
                    - key: ca.crt
                      path: ca.crt
              - secret:
                  name: cockroach-root
                  items:
                    - key: tls.crt
                      path: client.root.crt
                    - key: tls.key
                      path: client.root.key
            defaultMode: 256
{{ end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sqlpad
  name: sqlpad
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sqlpad
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: sqlpad
  name: sqlpad
  namespace: {{ .Values.namespace }}
spec:
  defaultBackend:
    service:
      name: sqlpad
      port:
        number: 3000
  rules:
    - host: sqlpad.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: sqlpad
                port:
                  number: 3000
            path: /
            pathType: ImplementationSpecific
---
{{end}}
