{{ if eq .Values.database "aurora-postgres" }}
kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Values.dbUrl }}
{{ end }}
