= {project_name} HTTP metrics

This section describe metrics for monitoring the {project_name} HTTP requests processing.

== Processing time

The processing time is exposed by these metrics, to monitor the {project_name} performance and how long it takes to processing the requests.

TIP: On a healthy cluster, the average processing time will remain stable.
Spikes or increases on the processing time may be an early indication that some node is under load.

====
*Tags*

* `outcome`: A more general outcome tag.
* `status`: The HTTP status code.
* `uri`: The requested URI.
====

|===
|Metric |Description

m| http_server_requests_seconds_count
| The total number of requests processed.

m| http_server_requests_seconds_sum
| The total duration for all the requests processed.
|===

include::partial$/running/metrics/histogram_note.adoc[]

== Active requests

The current number of active requests is also available.

|===
|Metric |Description

m| http_server_active_requests
| The current number of active requests

|===



== Bandwidth

The metrics below helps to monitor the bandwidth used by {project_name} and consumed by the requests and responses exchanged.

|===
|Metric |Description

m| http_server_bytes_written_count
| The total number of responses sent.

m| http_server_bytes_written_sum
| The total number of bytes sent.

m| http_server_bytes_read_count
| The total number of requests received.

m| http_server_bytes_read_sum
| The total number of bytes received.

|===

include::partial$/running/metrics/histogram_note.adoc[]
