= Preparing Keycloak for testing
:description: In order to run the load tests, some configuration and entities need to be present.

{description}

== Prerequisites

. A running Keycloak installation.
+
To set up a new instance for testing, consider xref:kubernetes-guide::installation.adoc[] as it includes several observability tools.

== Configuration

Choose from the manual and the scripted configuration to set up a realm for a load test.
To set up a lot of realms, clients and users, consider using the xref:dataset-guide:ROOT:index.adoc[dataset provider].

=== Manual configuration

Some scenarios require that `User Registration` setting enabled.

. Select the realm that is used for testing.
. In the `Realm Settings`, choose the tab `Login` and enable the login screen customization `User Registration`.

Some scenarios require users with password:

. Create a user.
. In the menu:Credentials[] tab, set a password.
Make the password non-temporary as Keycloak would otherwise prompt for a password.

Some scenarios require a service account with the clientId `gatling`:

. Select the realm that is used for testing.
. Create a client with the name `gatling`.
. Set access type to `confidential`.
. Check `Service Account Enabled`.
. Enter a valid redirect uri (e.g. `http://localhost`).
. Click save.
. Change to the tab `Sevice Account Roles`.
. Select for `realm-management` in the `Client Roles` listbox.
. Assign the roles, based on the below role-mapping table for the respective load simulation scenario.
. The client secret to be passed to the tests can be copied from the `Credentials` tab.

[cols="<,^"]
|===
|Scenario Name |Assigned Roles

|CreateClient |manage-clients, view-users
|CreateDeleteClient |manage-clients, view-users
|CrawlUsers |manage-clients, view-users
|CreateRole |manage-realm
|CreateDeleteRole |manage-realm
|CreateClientScope |manage-clients, view-users
|CreateDeleteClientScope |manage-clients, view-users
|CreateGroup |manage-users
|CreateDeleteGroup |manage-users
|CreateUsers |manage-users
|CreateDeleteUsers |manage-users
|===

=== Scripted configuration

Instead of following the above manual steps, you can use this link:{github-files}/benchmark/initialize-benchmark-entities.sh[initialize-benchmark-entities.sh] script to do the setup for you.

Login to the Keycloak server using the kcadm cli script, which comes with any Keycloak distribution

[source,shell]
----
$KEYCLOAK_HOME/bin/kcadm.sh config credentials --server http://localhost:8081/auth --realm master --user admin --password admin

----

and then run this, for creating the needed realm, client and user

[source,shell]
----
./initialize-benchmark-entities.sh -r test-realm -c gatling -u user-0

----

or use a `-d` flag, to recreate the entities from scratch for any reason

[source,shell]
----
./initialize-benchmark-entities.sh -r test-realm -c gatling -u user-0 -d

----

