= Release

If you need to do changes in the "dataset" and then consume it for example from the Openshift pods, you may need the ability to push your changes to the Keycloak and the release it.

== How to release

. Make sure that everything needed is committed and pushed inside https://github.com/keycloak/keycloak-benchmark in the "main" branch.
Make sure that your local "main" branch has the same content.
+
----
git checkout main
git log -n 1
----
+
The commit number should be the same as the last commit inside https://github.com/keycloak/keycloak-benchmark/tree/main

. Try the "dry" run of the release:
+
----
git checkout main
mvn clean install
mvn release:clean release:prepare -DdryRun=true -Dtag=0.3
----

. Once it is all good, then do a real release (not just dry run):
+
----
mvn release:clean release:prepare -Dtag=0.3
----

. Check that commits in the https://github.com/keycloak/keycloak-benchmark/tree/main have your commits added (release commit and "next-version" commit) and also there is new tag under https://github.com/keycloak/keycloak-benchmark/tags
+
NOTE: There is likely no need to run `mvn release:perform` and deploy anything into the maven repository.
As long as someone wants to have dependency on this dataset, we may need to add this.
+
. Just clean now
+
----
mvn release:clean
----

. Go to your tab and build it locally (Replace with the actual tag version)
+
----
git checkout keycloak-benchmark-parent-0.1
mvn clean install
git checkout main
----
+
Check that this file (corresponding to your released version) exists on your laptop: `<YOUR_HOME>/.m2/repository/org/keycloak/keycloak-benchmark-dataset/0.1/keycloak-benchmark-dataset-0.1.jar`

If everything is OK, a GitHub release is going to be created automatically with all artifacts that should be available for download.

