= Releasing a new version

We will release a new version of Keycloak Benchmark
when we have one or more breaking backward compatibility changes with prior versions of Keycloak releases.
The changes are often in the "dataset" provider but are not limited to that.

== Release steps

. Make sure that everything needed is committed
and pushed inside https://github.com/keycloak/keycloak-benchmark in the `main` branch.
On your local from the HEAD of the `main` branch,
create a new release branch with this signature `XX-release`, for example `25.0-release`.
In that release branch,
make the below series of updates
to upgrade the version which are required for a Keycloak Benchmark's SNAPSHOT release to be successful.
+
. Update the latest supported version of Keycloak in the link:{github-files}/.github/workflows/snapshot.yml[Snapshot release GitHub workflow YAML] in the `--notes 'Latest version built from` with a line similar to `<br>Use this with Keycloak 25.x`. This is further used by the `Snapshot` GitHub workflow to create the snapshot releases and imprint the artifacts with the specific Keycloak release.
+
. Now perform a project wide search for the below keywords and replace them with the respective ones appropriately as per the release.
* Search for `nightly` and replace it with `25.0.1`, if the release is performed against the `Keycloak 25.0.1` build.
* Search for `keycloak-999.0.0-SNAPSHOT` and replace it with `keycloak-25.0.1`, if the release is performed against the `Keycloak 25.0.1` build.
* Search for `999.0.0` and replace it with `25.0.1`, if the release is performed against the `Keycloak 25.0.1` build.
+
. Now push your changes from your local `XX-release` branch to the remote `XX-release` branch, which in turn generates the specific artifacts necessary for the SNAPSHOT release.

