= Scenario overview

These are the available test scenarios:

xref:scenario/authorization-code.adoc[`keycloak.scenario.authentication.AuthorizationCode`]:: Authorization Code Grant Type

`keycloak.scenario.authentication.LoginUserPassword`:: Browser Login (only Authorization Endpoint.
After username+password login, there is no exchange of OAuth2 "code" for the tokens)

`keycloak.scenario.authentication.ClientSecret`:: Client Secret (Client Credentials Grant)

`keycloak.scenario.admin.CreateDeleteClient`:: Create and delete clients (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateClient`:: Create clients (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteUsers`:: Create and delete users (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateUsers`:: Create users.. (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteRole`:: Create and delete roles (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateRole`:: Create roles (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteGroup`:: Create and delete groups (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateGroup`:: Create groups (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteClientScope`:: Create and delete client scopes (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateClientScope`:: Create client scope (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.UserCrawl`:: Crawls all users page by page (requires `--client-secret=<client secret for gatling client>`)

xref:scenario/create-realm.adoc[`keycloak.scenario.admin.CreateRealm`]:: Create realms (requires `--admin-username=<admin login>` and `--admin-password=<admin password>`)

xref:scenario/create-realm.adoc[`keycloak.scenario.admin.CreateDeleteRealm`]:: Create and immediately delete realms (requires `--admin-username=<admin login>` and `--admin-password=<admin password>`)

