= Scenario overview

These are the available test scenarios:

xref:scenario/authorization-code.adoc[`keycloak.scenario.authentication.AuthorizationCode`]:: Authorization Code Grant Type

`keycloak.scenario.authentication.LoginUserPassword`:: Browser Login (only Authorization Endpoint.
After username+password login, there is no exchange of OAuth2 "code" for the tokens)

`keycloak.scenario.authentication.ClientSecret`:: Client Secret (Client Credentials Grant)

`keycloak.scenario.admin.CreateDeleteClient`:: Create and delete clients (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateClients`:: Create clients (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteUsers`:: Create and delete users (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateUsers`:: Create users.. (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteRoles`:: Create and delete roles (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateRoles`:: Create roles (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteGroups`:: Create and delete groups (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateGroups`:: Create groups (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateDeleteClientScopes`:: Create and delete client scopes (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.CreateClientScopes`:: Create client scope (requires `--client-secret=<client secret for gatling client>`)

`keycloak.scenario.admin.UserCrawl`:: Crawls all users page by page (requires `--client-secret=<client secret for gatling client>`)

xref:scenario/list-sessions.adoc[`keycloak.scenario.admin.ListSessions`]:: Create User and Client sessions (requires `--admin-username=<admin login>` and `--admin-password=<admin password>`)

xref:scenario/create-realms.adoc[`keycloak.scenario.admin.CreateRealms`]:: Create realms (requires `--admin-username=<admin login>` and `--admin-password=<admin password>`)

xref:scenario/create-realms.adoc[`keycloak.scenario.admin.CreateDeleteRealms`]:: Create and immediately delete realms (requires `--admin-username=<admin login>` and `--admin-password=<admin password>`)

xref:scenario/basic-get.adoc[`keycloak.scenario.basic.Get`]:: Repeatedly call a specific URL with HTTP GET and report and check the status code

