= Aurora PostgreSQL: Multiple Availability Zone Deployment
:description: This guide describes the procedures required to deploy an AWS Aurora PostgreSQL database across multiple AWS availability
zones.

{description}

== Audience

This guide describes how to deploy an Aurora PostgreSQL instance across multiple availability-zones in order to
tolerate one or more availability-zone failures in a given AWS region.

== Architecture
Aurora DB clusters consist of multiple Aurora DB instances, with one instance designated as the primary writer and all
others as backup readers. To ensure high-availability in the event of availability zone failures, Aurora allows DB instances
to be deployed across multiple zones in a single AWS region. In the event of a failure on the availability-zone hosting
the Primary DB instance, Aurora automatically heals itself and promotes a reader instance from a non-failed availability-zone
to be the new writer instance.

.Aurora Multiple Availability Zone Deployment
image::aurora/aurora-multi-az.dio.svg[]

See the https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html[AWS Aurora documentation] for more details on the semantics provided by Aurora DBs.

NOTE: This guide follows AWS best-practices and creates a private Aurora DB that is not exposed over the internet. In order
to access the DB from a ROSA cluster it's necessary for a xref:running/aurora-peering-connections.adoc[peering-connection]
to be established.

== Procedure
The following procedure is split into two parts. First, we create an Aurora Multi-AZ DB cluster with the name "keycloak-aurora"
in eu-west-1. Then we create a peering-connection between our ROSA cluster(s) and the Aurora VPC to allow applications
deployed on the ROSA clusters to be able to establish connections with the DB.

=== Create Aurora DB Cluster

include::partial$aurora/aurora-multiaz-create-procedure.adoc[]

=== Establish Peering Connections with ROSA clusters

The following steps must be repeated for each ROSA cluster which contains a Keycloak deployment.

include::partial$aurora/aurora-create-peering-connections.adoc[]

== Verifying the connection

include::partial$aurora/aurora-verify-peering-connections.adoc[]

== Deploying Keycloak

Now that an Aurora DB has been established and linked with all of your ROSA clusters, the next step is to
xref:running/keycloak-deployment.adoc[Deploy Keycloak] with the JDBC url configured to use the Aurora DB writer
endpoint. Todo this we create a `Keycloak` CR outlined in the xref:running/keycloak-deployment.adoc[] guide, however
we modify the following elements:


. Update `spec.db.url` to be `jdbc:postgresql://$HOST$:5432/keycloak` where `$HOST` is the
<<aurora-writer-url, Aurora writer endpoint URL>>.

. Ensure that the Secrets referenced by `spec.db.usernameSecret` and `spec.db.passwordSecret` contain usernames and
passwords defined when creating Aurora.
