= Failover Recovery
:description: This guide describes the procedures to recover the primary site back to operation.

include::partial$running/infinispan-attributes.adoc[]

{description}

// Infinispan -> trigger state transfer secondary -> primary (assumes empty caches)
// Aurora -> switch to primary site?
// Keycloak -> switch to primary site?
// Route53 -> switch to primary site

== Audience

This guide contains the procedures required to bring the primary site back to operation.
After a crash event in the primary site, the load balance will switch to the secondary site.
Recovery from the crash implies bringing the primary site online and perform the necessary recovery operations for {ispn} and Aurora.

See xref:running/index.adoc[] for additional guides.

== Procedures

=== {ispn} Cluster

For the context of this guide, `{site-a}` is the primary site, recovering back to operation, and `{site-b}` is the secondary site, running in production.

include::partial$running/infinispan-batchcr-intro.adoc[]

WARNING: It assumes that the primary site (`{site-a}`) starts with empty caches.

The `ConfigMap` with the {ispn} CLI operations are as follows:

.Checks the cross-site status for all caches backing up to `{site-a}`.
[source,yaml]
----
include::example$helm/ispn-site-b.yaml[tag=infinispan-crossdc-status]
----

.Starts a cross-site state transfer for all caches backing up to `{site-a}`.
[source,yaml]
----
include::example$helm/ispn-site-b.yaml[tag=infinispan-crossdc-push-state]
----

.Checks the cross-site state transfer progress.
[source,yaml]
----
include::example$helm/ispn-site-b.yaml[tag=infinispan-crossdc-push-state-status]
----

.Resets the cross-site state transfer progress after its completion.
[source,yaml]
----
include::example$helm/ispn-site-b.yaml[tag=infinispan-crossdc-reset-push-state-status]
----

[#running-infinispan-batch]
==== Running {ispn} Batch

include::partial$running/infinispan-running-batch.adoc[]

==== Procedures

After the {ispn} in the primary site is back online and joined the cross-site channel (see xref:running/infinispan-crossdc-deployment.adoc#verifying-the-deployment[verifying the {ispn} deployment]), the state transfer must be manually started from the secondary site.

It transfers the full state from the secondary site to the primary site, and it must be completed before the primary site can start handling incoming requests.

. Login into your secondary site

. Run the `crossdc-push-state-status` Batch CR (see xref:#running-infinispan-batch[]).

. Check the replication status is `ONLINE` for all caches with `crossdc-status` Batch CR.

. Wait for the state transfer to completed by checking the output of the Batch CR `crossdc-push-state-status`

. If an error is reported by step 4, try to repeat the operations from step 2.

. Finally, clear the state transfer status with Batch CR `crossdc-reset-push-state-status` and delete all Batch CRs created.

WARNING: Transferring the full state may impact the {ispn} cluster perform by increasing the response time and/or resources usage.

Both {ispn} clusters are in sync and the switchover from secondary back to the primary site can be performed.

=== AWS Aurora Database

Section under development.

=== Keycloak Cluster

Section under development.

=== Route53

Section under development.
