= {ispn} Deployment: Single Cluster
:description: This describes the {ispn} deployment in a single cluster environment.

include::partial$running/infinispan-attributes.adoc[]

{description}

== Audience

This guide describes the procedure required to deploy {ispn} in a single cluster environment.
For simplicity, this guide uses the minimum configuration possible that allows {project_name} to be used with an external {ispn}.

See xref:running/index.adoc[] for additional guides.

== Prerequisites

include::partial$/running/infinispan-prerequisites.adoc[]

== Procedure

include::partial$/running/infinispan-install-operator.adoc[]
include::partial$/running/infinispan-credentials.adoc[]

. Create an {ispn} cluster.
+
The {operator-docs}#creating-clusters[Creating {ispn} clusters] documentation provides all the information on how to create and configure your {ispn} cluster.
+
.{ispn} CR
[source,yaml]
----
include::example$helm/ispn-single.yaml[tag=infinispan-single]
----
<1> The cluster name
<2> Allows the cluster to be monitored by Prometheus
<3> If using a custom credential, configure here the secret name created in the previous step.

. Create the caches for {project_name}.
+
{project_name} requires the following caches to be present: `sessions`, `actionTokens`, `authenticationSessions`, `offlineSessions`, `clientSessions`, `offlineClientSessions`, `loginFailures`, and `work`.
+
Use the {operator-docs}#creating-caches[{ispn} Cache CR] to deploy the caches in the {ispn} cluster.
+
See below for an example for the `sessions` cache.
Repeat this for all other caches listed above.
+
.Cache CR for the `sessions` cache
[source,yaml]
----
include::example$helm/ispn-single.yaml[tag=infinispan-cache-sessions]
----
+
The https://infinispan.org/docs/stable/titles/configuring/configuring.html[{ispn} documentation] contains more detail about cache configuration ands its options.

== Verifying the deployment

Confirm that the {ispn} cluster is formed.

.Wait until the {ispn} cluster is formed
[source,bash,subs="+attributes"]
----
kubectl wait --for condition=WellFormed --timeout=300s infinispans.infinispan.org -n {ns} {cluster-name}
----
