= {keycloak} with external {ispn}
:description: This describes configuration tweaks and changes on how to run {keycloak} with an external {ispn} Deployment under load.

{description}

== Audience

This guide describes advanced {ispn} configurations for {keycloak} on Kubernetes.

While the Helm charts in the {keycloak} Benchmark project mix different aspects of production style deployments with instrumentation and monitoring, this documentation focuses on the minimal changes which admins can implement in their own deployments.

See xref:running/index.adoc[] for additional guides.

== Prerequisites

* OpenShift or Kubernetes cluster running.
* Existing xref:running/keycloak-deployment.adoc[Basic {keycloak} deployment] as it will be extended.
* Existing {ispn} deployment, for example, one of xref:running/infinispan-deployment.adoc[] or xref:running/keycloak-with-external-infinispan.adoc[].

== Procedure

. Prepare an {ispn} Cache configuration XML from the file `cache-ispn.xml` which is part of the {keycloak} distribution:
.. For each `distributed-cache` entry, add the tags `<persistence />` as shown below.
+
[source,xml,indent=0]
----
include::example$helm-keycloak-config/kcb-infinispan-cache-remote-store-config.xml[tag=keycloak-ispn-remotestore]
----
<1> New tag `<persistence />` to connect it to the remote store.
<2> For the address to the remote store, reference two environment variables for host name and port number.
<3> For authentication, reference two environment variables for username and password.
<4> To secure the remote store connection, use the Kubernetes mechanisms of the pre-configured truststore.

.. Prepare an {ispn} Cache configuration XML from the file `cache-ispn.xml` which is part of the {keycloak} distribution:
For each `replicated-cache` entry, add the tag `<persistence />` as shown below.
+
[source,xml,indent=0]
----
include::example$helm-keycloak-config/kcb-infinispan-cache-remote-store-config.xml[tag=keycloak-ispn-remotestore-work]
----

. Place the {ispn} Cache configuration XML in a ConfigMap.
+
[source,yaml]
----
include::example$helm/keycloak-ispn.yaml[tag=keycloak-ispn-configmap]
...
----

. Create a Secret with the username and password to connect to the external {ispn} deployment:
+
[source,yaml]
----
include::example$helm/keycloak-ispn.yaml[tag=keycloak-ispn-secret]
----

. Extend the {keycloak} Custom Resource with `additionalOptions` and extend the `podTemplate` as shown below.
+
[NOTE]
====
* The new `additionalOptions` entries starting with `remote-store` used here are not official {keycloak} configurations.
Instead, they provide their values to environment variables that are then referenced in the {ispn} XML configuration.
* All the memory, resource and database configurations are skipped from the CR below as they have been described in xref:./keycloak-deployment.adoc[] already.
Admins should leave those configurations untouched.
====
+
[source,yaml]
----
include::example$helm/keycloak-ispn.yaml[tag=keycloak-ispn]
----
<1> Custom cache configuration XML file definition, which includes configuration for remote or embedded {ispn} store.
<2> The hostname and port of the remote cache {ispn} cluster.
<3> The credentials required, username and password, to access the remote cache {ispn} cluster.
<4> `jboss.site.name` is an arbitrary {ispn} site name which {keycloak} needs for its embedded {ispn} deployment when a remote store is used. This site name is related only to the embedded {ispn} and does not need to match any value from the external {ispn} deployment.
<5> Mounting the cache configuration Volume in Kubernetes.
However, matching the `jboss.site.name` with the external {ispn} deployment site name helps debugging possible future issues.
If you are using multiple sites for {keycloak} in a cross-DC setup like xref::running/infinispan-crossdc-deployment.adoc[], the site name must be different in each site.
<6> Defining the cache configuration Volume using the already created ConfigMap in Kubernetes.

