= Keycloak Deployment
:description: This describes configuration tweaks and changes on how to run a Keycloak Deployment under load.

{description}

== Audience

This guide describes advanced Keycloak configurations for Kubernetes which are load tested and will recover from single Pod failures.

While the Helm charts in the Keycloak Benchmark project mix different aspects of production style deployments with instrumentation and monitoring, this documentation focuses on a minimal deployment with optional add-ons which admins can opt in for their own deployments.

See xref:running/index.adoc[] for additional guides.

== Prerequisites

* OpenShift or Kubernetes cluster running
* Understanding of a https://www.keycloak.org/operator/basic-deployment[Basic Keycloak deployment]

== Procedure

// TODO: Which settings to include in the standard recipe, and which in separate optional steps below

. Determine the sizing of the deployment using xref:benchmark-guide::report/rosa-benchmark-key-results.adoc[].

. https://www.keycloak.org/operator/installation[Deploy Keycloak Operator].

. Deploy the Keycloak CR with the following values with the resource requests and limits calculated in the first step:
+
[source,yaml]
----
include::example$helm/keycloak.yaml[tag=keycloak]
----
<1> The database connection pool initial, max and min size should be identical to allow statement caching for the database.
See xref:./concepts/database-connections.adoc[] for details.
<2> To be able to analyze the system under load, enable the metrics endpoint.
The downside of the setting is that the metrics will be available at the external Keycloak endpoint, so you must add a filter so that the endpoint is not available from the outside.
Use a reverse proxy in front of Keycloak to filter out those URLs.
<3> The internal JGroup thread pools is by default set up for 200 threads maximum.
The number of all Keycloak threads in the stateful set should not exceed the number of JGroup threads to avoid a JGroup thread pool exhaustion which could stall Keycloak request processing.
It might be beneficial to limit the number of Keycloak threads even further, as too many concurrent threads will lead to throttling by Kubernetes once the requested CPU limit is reached.
See xref:./concepts/threads.adoc[] for details.
<4> The JVM options set additional parameters:
* `jgroups.thread_dumps_threshold` ensures that a log message "`thread pool is full`" appears once the JGroup thread pool is full for the first time. See xref:./concepts/threads.adoc[] for details.
* Adjust the memory settings for the heap.
<5> Probes will be delayed when requests queue up under load, and fail when a load is shed.
So the best way to run Keycloak in Kubernetes would be to disable those probes, for now.
See xref:./concepts/threads.adoc#probes[Probes] for details.

== Optional: Load shedding

Keycloak currently lacks a mechanism for load shedding.
There are currently different methods in evaluation.

The only way to do this in Keycloak 22 is to specify a Quarkus thread pool queue size. Unfortunately, this can cause side effects to block, for example, the health probes. See https://github.com/keycloak/keycloak/pull/23920[keycloak#23920] for the discussion.
See below if you want to give it a try anyway.

A more sophisticated solution is discussed in https://github.com/keycloak/keycloak/issues/23340[keycloak#23340] which migh arrive for Keycloak 23.

.Load shedding with Quarkus thread pool size
[source,yaml,indent=0]
----
            env:
include::example$helm/keycloak.yaml[tag=keycloak-queue-size]
----
<1> This limits the number of queued Keycloak requests. All exceeding requests are served with an HTTP 500 error and logged.
See xref:./concepts/threads.adoc#load-shedding[load shedding] for details.

== Optional: Disable sticky sessions

When running on OpenShift and the default passthrough Ingress setup as provided by the Keycloak Operator, the load balancing done by HAProxy is done using sticky sessions based on the source's IP address.
When running load tests, or when having a reverse proxy in front of HAProxy, you might want to disable this to avoid receiving all requests on a single Keycloak Pod.

Add the following supplementary configuration under the `spec` in the Keycloak Custom Resource to disable sticky sessions.

[source,yaml]
----
spec:
    ingress:
        enabled: true
        annotations:
          # When running load tests, disable sticky sessions on the OpenShift HAProxy router
          # to avoid receiving all requests on a single Keycloak Pod.
          haproxy.router.openshift.io/balance: roundrobin
          haproxy.router.openshift.io/disable_cookies: 'true'
----
