= AWS Global Accelerator Load Balancing
:description: This guide describes the procedure required to deploy an AWS global accelerator to handle failover between \
Multi-AZ Keycloak clusters.

{description}

== Audience

This guide describes how to deploy an AWS Global Accelerator instance to handle Keycloak client connection failover for multiple
availability-zone Keycloak deployments.

== Architecture

All Keycloak client requests are routed via an AWS Global Accelerator instance. It's the responsibility of the configured
accelerator to ensure that all requests are routed to the Primary cluster when it's available and healthy, or to the backup
cluster in the event of the primary availability-zone and/or Keycloak deployment failing. Utilising an AWS Global Accelerator
prevents clients from erroneously caching IP addresses of failed Keycloak deployments which is possible with DNS based
failover strategies.

.AWS Global Accelerator Failover
image::accelerator/accelerator-multi-az.dio.svg[]

An AWS Network Load Balancer (NLB) is created on both the Primary and Backup ROSA cluster in order to make the Keycloak
pods available as Endpoints to an AWS Global Accelerator instance. The Primary cluster endpoint is assigned a weight of
100 to ensure that all accelerator traffic is routed to this endpoint when this Keycloak deployment is healthy. Conversely,
the backup cluster is assigned a weight of 0 to ensure that traffic is only routed to this endpoint when the Primary
cluster's endpoint is no longer healthy.

== Prerequisites

* ROSA based Multi-AZ Keycloak deployment

== Procedure
. Create Network Load Balancers
+
For both the Primary and Backup cluster, perform the following:
+
.. Login to the ROSA cluster
+
.. Create a Kubernetes LoadBalancer service
+
.Command:
[source,bash]
----
cat <<EOF | oc apply -n $NAMESPACE -f - #<1>
  apiVersion: v1
  kind: Service
  metadata:
    name: accelerator-loadbalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health/live"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "https"#
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"# <2>
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"# <3>
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"# <4>
  spec:
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    selector:
      app: keycloak
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/managed-by: keycloak-operator
    sessionAffinity: None
    type: LoadBalancer
EOF
----
<1> `$NAMESPACE` should be replaced with the namespace of your Keycloak deployment
<2> How frequently the healthcheck probe is executed in seconds
<3> How many healthchecks must pass for the NLB to be considered healthy
<4> How many healthchecks must fail for the NLB to be considered unhealthy
+
.. Take note of the DNS hostname as this will be required later:
+
.Command:
[source,bash]
----
oc -n $NAMESPACE get svc accelerator-loadbalancer --template="{{range .status.loadBalancer.ingress}}{{.hostname}}{{end}}"
----
+
.Output:
[source,bash]
----
abab80a363ce8479ea9c4349d116bce2-6b65e8b4272fa4b5.elb.eu-west-1.amazonaws.com
----
+
. Create a Global Accelerator instance
+
.Command:
[source,bash]
----
aws globalaccelerator create-accelerator \
  --name example-accelerator \#<1>
  --ip-address-type DUAL_STACK \#<2>
  --region us-west-2 #<3>
----
<1> The name of the accelerator to be created, update as required
<2> Can be 'DUAL_STACK' or 'IPV4'
<3> All `globalaccelerator` commands must use the region 'us-west-2'
+
.Output:
[source,json]
----
{
    "Accelerator": {
        "AcceleratorArn": "arn:aws:globalaccelerator::606671647913:accelerator/e35a94dd-391f-4e3e-9a3d-d5ad22a78c71",#<1>
        "Name": "example-accelerator",
        "IpAddressType": "DUAL_STACK",
        "Enabled": true,
        "IpSets": [
            {
                "IpFamily": "IPv4",
                "IpAddresses": [
                    "75.2.42.125",
                    "99.83.132.135"
                ],
                "IpAddressFamily": "IPv4"
            },
            {
                "IpFamily": "IPv6",
                "IpAddresses": [
                    "2600:9000:a400:4092:88f3:82e2:e5b2:e686",
                    "2600:9000:a516:b4ef:157e:4cbd:7b48:20f1"
                ],
                "IpAddressFamily": "IPv6"
            }
        ],
        "DnsName": "a099f799900e5b10d.awsglobalaccelerator.com",#<2>
        "Status": "IN_PROGRESS",
        "CreatedTime": "2023-11-13T15:46:40+00:00",
        "LastModifiedTime": "2023-11-13T15:46:42+00:00",
        "DualStackDnsName": "ac86191ca5121e885.dualstack.awsglobalaccelerator.com"#<3>
    }
}

----
<1> The ARN associated with the created Accelerator instance, this will be used in subsequent commands
<2> The DNS name which IPv4 Keycloak clients should connect to
<3> The DNS name which IPv6 Keycloak clients should connect to
+
. Create a Listener for the accelerator
+
.Command:
[source,bash]
----
aws globalaccelerator create-listener \
  --accelerator-arn 'arn:aws:globalaccelerator::606671647913:accelerator/e35a94dd-391f-4e3e-9a3d-d5ad22a78c71' \
  --port-ranges '[{"FromPort":443,"ToPort":443}]' \
  --protocol TCP \
  --region us-west-2
----
+
.Output:
[source,json]
----
{
    "Listener": {
        "ListenerArn": "arn:aws:globalaccelerator::606671647913:accelerator/e35a94dd-391f-4e3e-9a3d-d5ad22a78c71/listener/1f396d40",
        "PortRanges": [
            {
                "FromPort": 443,
                "ToPort": 443
            }
        ],
        "Protocol": "TCP",
        "ClientAffinity": "NONE"
    }
}
----
+
. Create an Endpoint Group for the Listener
+
.Command:
[source,bash]
----
PRIMARY_ENDPOINT_ARN=$(aws elbv2 describe-load-balancers \
    --query "LoadBalancers[?DNSName=='abab80a363ce8479ea9c4349d116bce2-6b65e8b4272fa4b5.elb.eu-west-1.amazonaws.com'].LoadBalancerArn" \#<1>
    --region eu-west-1 \#<2>
    --output text
)
BACKUP_ENDPOINT_ARN=$(aws elbv2 describe-load-balancers \
    --query "LoadBalancers[?DNSName=='a1c76566e3c334e4ab7b762d9f8dcbcf-985941f9c8d108d4.elb.eu-west-1.amazonaws.com'].LoadBalancerArn" \#<1>
    --region eu-west-1 \#<2>
    --output text
)
ENDPOINTS='[
  {
    "EndpointId": "'${PRIMARY_ENDPOINT_ARN}'",
    "Weight": 100,
    "ClientIPPreservationEnabled": false
  },
  {
    "EndpointId": "'${BACKUP_ENDPOINT_ARN}'",
    "Weight": 0,
    "ClientIPPreservationEnabled": false
  }
]'
aws globalaccelerator create-endpoint-group \
  --listener-arn 'arn:aws:globalaccelerator::606671647913:accelerator/e35a94dd-391f-4e3e-9a3d-d5ad22a78c71/listener/1f396d40' \#<2>
  --traffic-dial-percentage 100 \
  --endpoint-configurations ${ENDPOINTS} \
  --endpoint-group-region eu-west-1 \#<3>
  --region us-west-2
----
<1> The DNS hostname of the Cluster's NLB
<2> The ARN of the Listener created in the previous step
<3> This should be the AWS region that hosts both the Primary and Backup cluster
+
.Output:
[source,json]
----
{
    "EndpointGroup": {
        "EndpointGroupArn": "arn:aws:globalaccelerator::606671647913:accelerator/e35a94dd-391f-4e3e-9a3d-d5ad22a78c71/listener/1f396d40/endpoint-group/2581af0dc700",
        "EndpointGroupRegion": "eu-west-1",
        "EndpointDescriptions": [
            {
                "EndpointId": "arn:aws:elasticloadbalancing:eu-west-1:606671647913:loadbalancer/net/abab80a363ce8479ea9c4349d116bce2/6b65e8b4272fa4b5",
                "Weight": 100,
                "HealthState": "HEALTHY",
                "ClientIPPreservationEnabled": false
            },
            {
                "EndpointId": "arn:aws:elasticloadbalancing:eu-west-1:606671647913:loadbalancer/net/a1c76566e3c334e4ab7b762d9f8dcbcf/985941f9c8d108d4",
                "Weight": 0,
                "HealthState": "UNHEALTHY",
                "ClientIPPreservationEnabled": false
            }
        ],
        "TrafficDialPercentage": 100.0,
        "HealthCheckPort": 443,
        "HealthCheckProtocol": "TCP",
        "HealthCheckPath": "undefined",
        "HealthCheckIntervalSeconds": 30,
        "ThresholdCount": 3
    }
}
----
+
. Update/Create Keycloak Deployment
+
For both the Primary and Backup cluster, perform the following:
+
.. Login to the ROSA cluster
+
.. Ensure the Keycloak CR has the following configuration
+
[source,yaml]
----
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  hostname:
    hostname: $HOSTNAME # <1>
  ingress:
    enabled: false # <2>
----
<1> The hostname clients use to connect to Keycloak
<2> Disable the default ingress as all Keycloak access should be via the provisioned NLB
+
To ensure that request forwarding works as expected, it's necessary for the Keycloak CR to specify the hostname through
which clients will access the Keycloak instances. This can either be the `DualStackDnsName` or `DnsName` hostname associated
with the Global Accelerator. Alternatively, this could be a more friendly hostname which utilises the Accelerator's IP
addresses or one of the aforementioned hostnames.

== Verify
To verify that the Global Accelerator is correctly configured to connect to the Primary cluster, navigate to the Accelerator's
`DnsName` or `DualStackDnsName` in your browser, and you should be presented with the Keycloak admin console.

To test failover works as expected, login to the Primary cluster and scale the Keycloak deployment to 0 pods. This will
cause the health checks on the Primary's NLB to fail and the accelerator should route traffic to the Keycloak pods on the
Backup cluster.
