= Out-of-sync datacenters Recovery
:description: This guide describes the steps to bring the secondary site up to date to the primary site after a network partition.

include::partial$running/infinispan-attributes.adoc[]

// used by the CLI commands to avoid duplicating the code.
:stale-site: secondary
:keep-site: primary
:keep-site-name: {site-a-cr}
:stale-site-name: {site-b-cr}

{description}

== Audience

This guide describes the procedures required to synchronize the secondary site after a temporary disconnection between sites.

See xref:running/index.adoc[] for additional guides.

=== {ispn} Cluster

For the context of this guide, `{site-a}` is the primary site and `{site-b}` is the secondary site.

Network partitions may happen between the site and the replication between the {ispn} cluster will stop.
Manual steps described in this guide bring both site back in sync.

WARNING: Transferring the full state may impact the {ispn} cluster perform by increasing the response time and/or resources usage.

First procedure is to delete the stale data from the secondary site.

. Login into your secondary site.

. Shutdown {keycloak}. This will clear all {keycloak} caches, and it prevents the state of {keycloak} from being out-of-sync with {ispn}.
+
When deploying {keycloak} using the {keycloak} Operator, change the number of {keycloak} instances in the {keycloak} Custom Resource to 0.

include::partial$running/infinispan-cli-connect.adoc[]

include::partial$running/infinispan-cli-clear-caches.adoc[]

Now we are ready to transfer the state from the primary site to the secondary site.

. Login into your primary site

include::partial$running/infinispan-cli-connect.adoc[]

include::partial$running/infinispan-cli-state-transfer.adoc[]

As now the state is available in the secondary datacenter, {keycloak} can be started again:

. Login into your secondary site.

. Startup {keycloak}.
+
When deploying {keycloak} using the {keycloak} Operator, change the number of {keycloak} instances in the {keycloak} Custom Resource to the original value.

=== AWS Aurora Database

No action required.

=== Route53

No action required.
