= Switchover to Secondary Site
:description: This guide describes the steps to switch from primary site to secondary site.

include::partial$running/infinispan-attributes.adoc[]

{description}

// Infinispan -> stop replication from secondary to primary
// Aurora -> switch to secondary site?
// Keycloak -> switch to secondary site?
// Route53 -> switch to secondary site

== Audience

This guide describes the procedures required to switch to the secondary site, and it assumes the primary site will be taken offline.

See xref:running/index.adoc[] for additional guides.

=== {ispn} Cluster

For the context of this guide, `{site-a}` is the primary site and `{site-b}` is the secondary site.

For taking a site offline, it is a good practice to disable the replication to it.
It prevents errors/delays when the channels are disconnected between the primary and the secondary site.

==== Procedures to transfer state from secondary to primary site

. Login into your secondary site

include::partial$running/infinispan-cli-connect.adoc[]

. Disable the replication to the primary site by running the following command:
+
[source,bash,subs="+attributes"]
----
site take-offline --all-caches --site={site-a-cr}
----
+
.Example
[source,bash,subs="+attributes"]
----
[{cluster-name}-0-29897@ISPN//containers/default]> site take-offline --all-caches --site={site-a-cr}
{
  "offlineClientSessions" : "ok",
  "authenticationSessions" : "ok",
  "sessions" : "ok",
  "clientSessions" : "ok",
  "work" : "ok",
  "offlineSessions" : "ok",
  "loginFailures" : "ok",
  "actionTokens" : "ok"
}
----

. Check the replication status is `offline`.
+
[source,bash,subs="+attributes"]
----
site status --all-caches --site={site-a-cr}
----
+
.Example
[source,bash,subs="+attributes"]
----
[{cluster-name}-0-29897@ISPN//containers/default]> site status --all-caches --site={site-a-cr}
{
  "status" : "offline"
}
----
+
If the status is not `offline`, repeat the previous step.

The {ispn} cluster in the secondary site is ready to handle requests without trying to replicate to the primary site.

=== AWS Aurora Database

include::partial$aurora/aurora-failover.adoc[]

=== Keycloak Cluster

No action required.

=== Route53

To force Route53 to mark the primary site as not available, edit the health check in AWS to point to a non-existent route (`health/down`)
It will take some minutes for the clients to notice the change, and traffic will gradually move over to the secondary site.
