= Switch back
:description: This guide describes the procedures to switch back to the primary site back after a failover or switchover to the secondary site.

include::partial$running/infinispan-attributes.adoc[]

// used by the CLI commands to avoid duplicating the code.
:stale-site: primary
:keep-site: secondary
:keep-site-name: {site-b-cr}
:stale-site-name: {site-a-cr}

{description}

// Infinispan -> trigger state transfer secondary -> primary (assumes empty caches)
// Aurora -> switch to primary site?
// Keycloak -> switch to primary site?
// Route53 -> switch to primary site

== Audience

This guide contains the procedures required to bring the primary site back to operation when the secondary site is handling all the traffic.
At the end of the guide, the primary site is online again and handles the traffic.

This is necessary when the primary site has lost its state in Infinispan, a network partition occurred between the primary and the secondary site while the secondary site was active, or the replication was disabled as described in xref:./switch-over.adoc[].

If the data in Infinispan on both sites is still in sync, the procedure for {ispn} can be skipped.

See xref:running/index.adoc[] for additional guides.

== Prerequisites

This assumes a xref:running/deployments/active-passive-sync.adoc[] setup.

== Procedures

=== {ispn} Cluster

For the context of this guide, `{site-a}` is the primary site, recovering back to operation, and `{site-b}` is the secondary site, running in production.

After the {ispn} in the primary site is back online and joined the cross-site channel (see xref:running/infinispan-crossdc-deployment.adoc#verifying-the-deployment[verifying the {ispn} deployment]), the state transfer must be manually started from the secondary site.

After clearing the state in the primary site, it transfers the full state from the secondary site to the primary site, and it must be completed before the primary site can start handling incoming requests.

WARNING: Transferring the full state may impact the {ispn} cluster perform by increasing the response time and/or resources usage.

The first procedure is to delete any stale data from the primary site.

. Login to the primary site.

. Shutdown Keycloak. This will clear all Keycloak caches, and it prevents the state of Keycloak from being out-of-sync with Infinispan.

include::partial$running/infinispan-cli-connect.adoc[]

include::partial$running/infinispan-cli-clear-caches.adoc[]

Now we are ready to transfer the state from the secondary site to the secondary site.

. Login into your secondary site.

include::partial$running/infinispan-cli-connect.adoc[]

include::partial$running/infinispan-cli-state-transfer.adoc[]

. Login to the primary site.

. Start Keycloak.

Both {ispn} clusters are in sync and the switchover from secondary back to the primary site can be performed.

=== AWS Aurora Database

include::partial$aurora/aurora-failover.adoc[]

=== Route53

If switching over to the secondary site has been triggered by changing the health endpoint, edit the health check in AWS to point to a correct endpoint (`health/live`).
It will take some minutes for the clients to notice the change, and traffic will gradually move over to the secondary site.
