= HA-Keycloak active/passive with synchronous replication
:navtitle: Active/passive with sync replication
:description: This concept describes the building blocks needed for a highly available active/passive setup and the behavior customers can expect.

{description}

== Audience

Solution architects and customers that require a high-available (HA) Keycloak deployment.
In this guide, we outline the requirements of the HA active/passive architecture, before exploring its benefits and tradeoffs.

After summarizing the architecture see <<building-blocks>> with the links to blueprints for each building block.

== Architecture

Two independent Keycloak deployments running in different datacenters connected with a low latency.
Entities like users, realms and clients are stored in a database which is running synchronously in the two datacenters.
Sessions are stored exclusively in Infinispan, which is also running synchronously in the two datacenters.
Offline sessions are stored in Infinispan, and can optionally be stored in the database as well.

image::crossdc/active-passive-sync.dio.svg[]

=== When to use this setup

Use this setup for customers who want to be able to fail over automatically in the event of a datacenter failure, and not to lose data or sessions.

Manual interactions might still be required to restore the redundancy after the failover.

=== Causes of data and service loss

While this setup aims for high availability, the following situations can still lead to service or data loss:

* Network failures between the datacenters or failures of components can lead to short service downtimes while those failures are detected.
The service will be restored automatically.
The system is degraded until the failures are detected and the backup cluster is promoted to service requests.

* Once failures occur in the communication between the datacenters, manual steps may be necessary to re-synchronize a degraded setup.
Future versions of Keycloak and Infinispan plan to reduce those manual operations.

* Degraded setups can lead to service or data loss if additional components fail.
Monitoring is necessary to detect degraded setups.

=== Failures this setup can survive

[%autowidth]
|===
| Failure | Recovery | RPO^1^ | RTO^2^

| Database node
| If the writer instance fails, the database can promote a reader instance in the same or other datacenter to be the new writer.
| No data loss
| Seconds to minutes (depending on the database)

| Keycloak node
| Multiple Keycloak instances run in each datacenter. If one instance fails, it takes a few seconds for the other nodes to notice the change, and some incoming requests might receive an error message or are delayed for some seconds.
| No data loss
| Less than one minute

| Infinispan node
| Multiple Infinispan instances run in each datacenter. If one instance fails, it takes a few seconds to the other nodes to notice the change. Sessions are stored in at least two Infinispan nodes, so a single node failure doesn't lead to data loss.
| No data loss
| Less than one minute

| Infinispan cluster failure
| If the Infinispan cluster fails in the active datacenter, Keycloak won't be able to communicate with the external Infinispan, and the Keycloak service will be unavailable.
Manual switchover to the secondary datacenter is recommended.
Future versions will detect this situation and do an automatic failover.

When the Infinispan cluster is restored, its data will be out-of-sync with Keycloak.
Manual operations are required to get Infinispan in the primary datacenter in sync with the secondary datacenter.
| Loss of service
| Human intervention required

| Connectivity Infinispan
| If the connectivity between the two datacenters is lost, session information can't be sent to the other datacenter.
Incoming requests might receive an error message or are delayed for some seconds.
The primary site marks the secondary site offline, and will stop sending data to the secondary.
The setup is degraded until the connection is restored and the session data is re-synchronized to the secondary datacenter.
| No data loss ^3^
| Less than one minute

| Connectivity Database
| If the connectivity between the two datacenters is lost, the synchronous replication will fail, and it might take some time for the primary site to mark the secondary offline.
Some requests might receive an error message or are delayed for some seconds.
Manual operations might be necessary depending on the database.
| No data loss ^3^
| Seconds to minutes (depending on the database)

| Primary Datacenter
| If none of the Keycloak nodes are available, the loadbalancer will detect the outage and redirect the traffic to the secondary site.
Some requests might receive an error message while the loadbalancer hasn't detected the primary datacenter failure.
The setup will be degraded until the primary site is back up and the session state has been manually synced from the secondary to the primary site.
| No data loss^3^
| Less than one minute

| Secondary Datacenter
| If the secondary datacenter is not available, it will take a moment for the primary Infinispan and database to mark the secondary datacenter offline.
Some requests might receive an error message while the detection takes place.
Once the secondary datacenter is up again, the session state needs to be manually synced from the primary site to the secondary site.
| No data loss^3^
| Less than one minute

|===

^1^: Recovery point objective, assuming all parts of the setup were healthy at the time this occurred. +
^2^: Recovery time objective. +
^3^: Manual operations needed to restore the degraded setup.

The statement "`No data loss`" depends on the setup not being degraded from previous failures, which includes completing any pending manual operations to resynchronize the state between the datacenters.

=== Known limitations

==== Upgrades

* On Keycloak major version upgrade, all session data (except offline session) might be lost as the data format is not guaranteed to be compatible between major versions.
* On any Infinispan upgrade (major, minor or patch), all session data might be lost as cross-DC communication is guaranteed to work only between identical versions of Infinispan.

==== Failovers

* A successful failover requires a setup not degraded from previous failures.
All manual operations like a re-synchronization after a previous failure must be complete to prevent a data loss.
Customers must use monitoring to ensure degradations are detected and handled in a timely manner.

==== Switchovers

* A successful switchover requires a setup not degraded from previous failures.
All manual operations like a re-synchronization after a previous failure must be complete to prevent a data loss.
Customers must use monitoring to ensure degradations are detected and handled in a timely manner.

==== Out-of-sync datacenters

* The datacenters can become out of sync when a synchronous Infinispan request fails.
This is currently difficult to monitor, and it would need a full manual re-sync of Infinispan to recover.
Monitoring the number of cache entries in both datacenters and Keycloak's log file can show when this would become necessary.
Future versions of Keycloak and Infinispan plan to automate this.

==== Manual operations

* Manual operations that re-synchronize the Infinispan state between the datacenters will issue a full state transfer which will put a stress on the system (network, CPU, Java heap in Infinispan and Keycloak).

=== Questions and answers

Why a synchronous database?::
A synchronously replicated database ensures that data written in the primary datacenter is always available in the secondary datacenter on failover and no data is lost.

Why a synchronous Infinispan replication?::
A synchronously replicated Infinispan ensures that sessions created, updated and deleted in the primary datacenter are always available in the secondary datacenter on failover and no data is lost.

Why low-latency between datacenters?::
Synchronous replication defers the response to the caller until the data is received at the secondary datacenter.
For a synchronous database replication and a synchronous Infinispan replication, a low latency is necessary as each request can have potentially multiple interactions between the datacenters when data is updated which would amplify the latency.

Why active-passive?::
Some databases support a single writer instance with a reader instance which is then promoted to be the new writer once the original writer fails.
In such a setup, it is beneficial for the latency to have the writer instance in the same datacenter as the currently active Keycloak.
Synchronous Infinispan replication can lead to deadlocks when entries in both datacenters are modified concurrently.

Is this setup limited to two datacenters?::
This setup could be extended to multiple datacenters, and there are no fundamental changes necessary to have, for example, three datacenters. Once more datacenters are added, the overall latency between the datacenters increases, and the likeliness of network failures, and therefore short downtimes, increases as well.
For now, it has been tested and documented with blueprints only for two datacenters.

Is a synchronous cluster less stable than an asynchronous cluster?::
An asynchronous setup would handle network failures between the datacenter gracefully, while the synchronous setup would delay requests and will throw errors to the caller where the asynchronous setup would have deferred the writes to the secondary datacenter.
But as the secondary site would never be fully up to date with the primary site, this could lead to data loss during failovers.
This would include:
+
--
* Lost logouts (sessions are still logged in the secondary datacenter that logged out in the primary datacenter at the point of failover)
* Lost changes like users being able to log in with their old passwords (database changes not replicated to secondary datacenter at the point of failover).
--
+
So there is effectively a tradeoff between availability and consistency.
For now, we've considered to rank consistency higher than availability with Keycloak.

[#building-blocks]
== Building blocks

The following building blocks are needed to set up the architecture described above.
Each building block links to a blueprint with an example configuration.
They are listed in the order in which they need to be installed.

=== Two datacenters with low-latency connection

Ensures that synchronous replication is available for both the database and Infinispan.

*Blueprint:* Two AWS Availablity Zones within the same AWS Region.

*Not considered:* Two regions on the same or different continents, as it would increase the latency and the likelihood of network failures.
Synchronous replication of databases as a services with Aurora Regional Deployments on AWS is only available within the same region.

=== Environment for Keycloak and Infinispan

Ensures that the instances are deployed and restarted as needed.

*Blueprint:* Red Hat OpenShift Service on AWS (ROSA) deployed in each availability zone.

*Not considered:* A stretched ROSA cluster which spans multiple availability zones, as this could be a single point of failure if misconfigured.

=== Database

A synchronously replicated database across two datacenters.

*Blueprint:* xref::running/aurora-multi-az.adoc[Amazon Aurora PostgreSQL Regional Deployment spanning two availability zones, connected to ROSA]

=== Infinispan

An Infinispan deployment which leverages the Infinispan's Cross-DC functionality.

*Blueprint:* xref::running/infinispan-crossdc-deployment.adoc[Deploy Infinispan using the Infinispan Operator on ROSA, and connect the two datacenters using Infinispan's Gossip Router].

*Not considered:* Direct interconnections between the OpenShift clusters on the network layer.
It might be considered in the future based on customer or community demand.

=== Loadbalancer

A loadbalancer which checks the `/health/live` URl of the Keycloak deployment in each datacenter.

*Blueprint:* xref:running/loadbalancing.adoc[].

*Not considered:* AWS Global Accelerator connecting to Red Hat OpenShift Service on AWS (ROSA) as it supports only weighted traffic routing and not active-passive failover.
To support active-passive failover, additional logic using, for example, AWS CloudWatch and AWS Lambda would be necessary to simulate the active-passive handling by adjusting the weights when the probes fail.

=== Keycloak

A clustered deployment of Keycloak in each datacenter, connected to an external Infinispan.

*Blueprint:* xref::running/keycloak-deployment.adoc[Deploy Keycloak using the Keycloak Operator on ROSA], and xref::running/keycloak-with-external-infinispan.adoc[connect it to the external Infinispan] and the Aurora database.
