= Installing minikube as a pre-requisite
:navtitle: Installing minikube
:description: minikube is a pre-requisite to provision Keycloak on Minikube.

{description}
It needs to be installed before the  xref:installation.adoc[] can begin.

== Installing minikube

The installation guide is available in the https://minikube.sigs.k8s.io/docs/start/[minikube installation guide].

== Optional installation steps for minikube

Add the following snippet to the file `~/.bashrc` to allow auto-completion of commands:

[source,bash]
----
source <(minikube completion bash)
----

The choice of Virtual Machine manger the user would install is probably dependent on the developer host Operating System. Below are the VM drivers which are tested and proven to be working without issue for the respective host OS.

=== Linux Host
KVM or Kernel-based Virtual Machine is a full virtualization solution for Linux on x86 hardware containing virtualization extensions. To learn more about it and its relevance to minikube, you can read the https://minikube.sigs.k8s.io/docs/drivers/kvm2/[docs].

Please take a note that the linux User needs to be added to the `libvirt` group using the below command.


[source,bash]
----
sudo usermod -aG libvirt $USER
----

Optionally you can use the below command to verify if the libvirt group exists and is updated with the user

The command:
[source,bash]
----
getent group libvirt
----

Should print an output like:

----
libvirt:x:981:johndoe
----

== Verifying the installation of minikube

The command:

[source,bash]
----
minikube version
----

Should print an output like:

----
minikube version: v1.25.2
commit: ...
----
