= Installing Infinispan operator in OpenShift as a pre-requisite
:navtitle: Installing Infinispan Operator
:description: Infinispan operator is a pre-requisite to deploy Infinispan clusters.

{description}
It needs to be completed before xref:openshift/installation-infinispan.adoc[] can begin.

== Prerequisites

This requires a running OpenShift instance, any OpenShift instance should work.

To set up OpenShift on AWS, use xref:prerequisite/prerequisite-rosa.adoc[Red Hat OpenShift Service on AWS (ROSA)].

IMPORTANT: The script `link:{github-files}/provision/aws/rosa_create_cluster.sh[rosa_create_cluster.sh]` automatically installs the Infinispan operator and no other action is required.

== Installation

. Check out the Git repository from https://github.com/keycloak/keycloak-benchmark[].

. Change to the folder `link:{github-files}/provision/infinispan[provision/infinispan]`.

. Login into your Openshift cluster.

. Run the `link:{github-files}/provision/infinispan/install_operator.sh[install_operator.sh]`.

NOTE: For an alternative installation procedure, check the https://infinispan.org/docs/infinispan-operator/main/operator.html#installation[Infinispan Documentation].
