= Installing minikube as a pre-requisite
:navtitle: Installing minikube
:description: minikube is a pre-requisite to provision Keycloak on Minikube.

{description}
It needs to be installed before the installation can begin.

== Installing minikube

The installation guide is available in the https://minikube.sigs.k8s.io/docs/start/[minikube installation guide].

== Optional installation steps for minikube

Add the following snippet to the file `~/.bashrc` to allow auto-completion of commands:

[source,bash]
----
source <(minikube completion bash)
----

The choice of Virtual Machine manger the user would install is probably dependent on the developer host operating system. Below are the VM drivers which are tested and proven to be working without issue for the respective host operating system.

=== Linux Host

KVM or Kernel-based Virtual Machine is a full virtualization solution for Linux on x86 hardware containing virtualization extensions. To learn more about it and its relevance to minikube, you can read the https://minikube.sigs.k8s.io/docs/drivers/kvm2/[docs].

Add Linux users to the `libvirt` group by using the following command:

[source,bash]
----
sudo usermod -aG libvirt $USER
----

Use the following command to verify if the `libvirt` group exists and the user is part of the group:

The command:
[source,bash]
----
getent group libvirt
----

Should print an output like:

----
libvirt:x:981:johndoe
----

== Verifying the installation of minikube

The command:

[source,bash]
----
minikube version
----

Should print an output like:

----
minikube version: v1.25.2
commit: ...
----
