= Installing OpenShift on AWS
:description: Red Hat OpenShift Service on AWS (ROSA) provides an OpenShift instance to run Keycloak.

{description}

== About

This module is intended to automate tasks around provisioning OpenShift clusters in AWS via ROSA tool, as described in the https://console.redhat.com/openshift/create/rosa/getstarted[ROSA installation guide].
The scripts are located in the folder `provision/aws` in this repository.

It will also install EFS as the storage provider for ReadWriteMany PersistentVolumeClaims with the storage class `efs-sc`.
See <<aws-efs-as-readwritemany-storage>> for more information.

== Prerequisites

. Install the https://aws.amazon.com/cli/[AWS CLI]
.. Run the commands to install the AWS command line tool:
+
[source,bash]
----
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install
----
.. Enable https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-completion.html[shell auto-completion] for bash by adding the following to your `~/.bashrc`:
+
----
complete -C '/usr/local/bin/aws_completer' aws
----
.. Create Access keys in https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/users[AWS Identity and Access Management ]
... Click on your user account
... Click on *Security credentials*
... Click on *Create access key* under *Access keys*
... Select *Command Line Interface (CLI)*
... Check the box for *I understand the above recommendation and want to proceed to create an access key*
... Click *Next*
... Enter `AWS CLI` as the description tag value and click on *Create access key*
... Leave the tab open for the next step
.. Run
+
----
aws configure
----

... AWS Access Key ID: *<copy/paste from above>*
... AWS Secret Access Key: *<copy/paste from above>*
... Default region name: *us-east-1*
... Default output format: <Leave blank>
.. Test using:
+
[source,bash]
----
aws sts get-caller-identity
----

. Perform the steps outlined in the https://console.redhat.com/openshift/create/rosa/getstarted[ROSA installation guide]:
.. Enable ROSA Service in AWS account
.. Download and install the ROSA command line tool
.. Create the service linked role for the Elastic Load Balancer
.. Log in to the ROSA CLI with your Red Hat account token and create AWS account roles and policies
.. Verify your credentials and quota

== Installation

The installation process is automated in the `rosa_create_cluster.sh` script in the folder `provision/aws` which takes its parameters from environment variables.

It loads environment variables pre-set in `.env` file inside the `aws/` directory.

The script creates the OCP cluster via `rosa create cluster` command, additionally it creates the required operator roles and OIDC provider.
After the installation process is finished, it creates a new admin user.

.Example `.env` file
----
CLUSTER_NAME=rosa-kcb
ADMIN_PASSWORD=needs-to-have-at-least-14-ascii-characters
VERSION=4.12.15
REGION=eu-central-1
COMPUTE_MACHINE_TYPE=m5.xlarge
MULTI_AZ=false
REPLICAS=3
----

=== Mandatory parameters

`VERSION`:: OCP cluster version.
`REGION`:: AWS region where the cluster should run.
`COMPUTE_MACHINE_TYPE`:: https://aws.amazon.com/ec2/instance-types/[AWS instance type] for the default OCP worker machine pool.
`MULTI_AZ`:: Boolean parameter to indicate whether the OCP cluster should span multiple Availability Zones within the selected region.
`REPLICAS`:: Number of worker nodes.
If multi-AZ installation is selected, then this needs to be a multiple of the number of AZs available in the region.
For example, if the region has 3 AZs, then replicas need to be set to some multiple of 3.
+
Use the following command to find out about the AZs in the region:
+
[source,bash,subs=+quotes]
----
aws ec2 describe-availability-zones --region _region-name_
----

=== Optional parameters

`CLUSTER_NAME`:: Name of the cluster.
If not set, the value of the `$(whoami)` command will be used.
`ADMIN_PASSWORD`:: Password for the `cluster-admin` user.
If not set, it is obtained from AWS Secrets Manager secret equal to `KEYCLOAK_MASTER_PASSWORD_SECRET_NAME` parameter.
`KEYCLOAK_MASTER_PASSWORD_SECRET_NAME`:: Name of the AWS Secrets Manager secret containing the password for the `cluster-admin` user.
Defaults to `keycloak-master-password`.

== Finding URLs

To find out about existing clusters and their URLs, use the following commands:

[source,bash,subs=+quotes]
----
rosa list clusters
rosa describe cluster -c _cluster-name_
----

== Re-create admin user

The above installation script creates an admin user automatically but in case the user needs to be re-created it can be done via the `rosa_recreate_admin.sh` script, providing the `CLUSTER_NAME` and optionally `ADMIN_PASSWORD` parameter.

== Scaling the cluster's nodes on demand

The standard setup of nodes might be too small for running a load test, at the same time using a different instance type and rebuilding the cluster takes a lot of time (about 45 minutes).
To scale the cluster on demand, the standard setup has a machine pool named `scaling` with instances of type `m5.4xlarge` spot instances which is scaled to zero by default.

To scale the machine pool at runtime, issue a command like the following, and the additional nodes will be available within about 5 minutes:

[source,bash,subs=+quotes]
----
rosa edit machinepool -c _**clustername**_ --min-replicas 3 --max-replicas 10 scaling
----

To scale down the cluster, use a command like the following:

[source,bash,subs=+quotes]
----
rosa edit machinepool -c _**clustername**_ --min-replicas 0 --max-replicas 0 scaling
----

To use different instance types, use `rosa create machinepool` to create additional machine pools

[#aws-efs-as-readwritemany-storage]
== AWS Elastic File Service as ReadWriteMany storage

This setup installs EFS as the storage provider for ReadWriteMany PersistentVolumeClaims with the storage class `efs-sc`.

Using the scripts `rosa_efs_create.sh` and `rosa_efs_delete.sh`, the EFS configuration can be added and removed.
Those are intended to be called from `rosa_create_cluster.sh` and `rosa_delete_cluster.sh` respectively.

Even when the scripts have completed, it might take a little while until the DNS in the PVC picks up the new IP address of the mount point.
In the meantime, you might see an error message like "`Failed to resolve server _file-system-id_.efs._aws-region_.amazonaws.com`".

The following docs have been used to set up EFS:

* https://docs.openshift.com/rosa/storage/container_storage_interface/osd-persistent-storage-aws-efs-csi.html[Official OpenShift docs: Setting up AWS Elastic File Service CSI Driver Operator]
* https://mobb.ninja/docs/rosa/aws-efs/[Community docs: Enabling the AWS EFS CSI Driver Operator on ROSA]
* https://access.redhat.com/articles/6966373[Red Hat knowledge base article: AWS EFS CSI Driver Operator installation guide in OCP]

== Rotate admin user password

The admin user password can be rotated via the `rosa_rotate_admin_password.sh` script.Note admin password for existing clusters are not updated.
The new password can be applied using script `rosa_recreate_admin.sh` with corresponding `CLUSTER_NAME` variable.

== Uninstallation

The uninstallation is handled by the `rosa_delete_cluster.sh` script.

The only required parameter is `CLUSTER_NAME`.

Additionally, it deletes the cluster's operator roles and OIDC provider, and the admin user.
