{{ if or (eq .Values.database "postgres") (eq .Values.database "mixed") }}
{{ if .Values.monitoring }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-exporter
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "config/pgexporter-queries.yaml").AsConfig | indent 2 }}
{{ end }}
{{ end }}
