{{ if or (eq .Values.database "postgres") (eq .Values.database "mixed") }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: 30009
  selector:
    app: postgres
{{ end }}
