{{ if or (eq .Values.database "postgres") (eq .Values.database "postgres+infinispan") }}
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      nodePort: {{ add 30009 (mul .Values.portOffset 100) }}
  selector:
    app: postgres
{{ end }}
