{
 "title": "Authentication Code SLO",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod_name",
    "query": "keycloak-0,keycloak-1,keycloak-2,keycloak-3,keycloak-4,keycloak-5"
   }
  ]
 },
 "panels": [
  { "title": "$pod_name stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod_name" },
  {
   "title": "$pod_name - Below 250ms response time percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_bucket{http_route=~\"(/realms/{realm}/protocol/{protocol}/token|/realms/{realm}/protocol/{protocol}/auth|/realms/{realm}/protocol/{protocol}/logout|realms/{realm}/login-actions/authenticate)\", le=\"250.0\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])) without (le) / rate(http_server_duration_count{http_route=~\"(/realms/{realm}/protocol/{protocol}/token|/realms/{realm}/protocol/{protocol}/auth|/realms/{realm}/protocol/{protocol}/logout|realms/{realm}/login-actions/authenticate)\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])",
     "legendFormat": "Percentage below 250ms {{http_route}}"
    },
    {
     "expr": "rate(vendor_cache_manager_keycloak_cache_realms_statistics_hits{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]) / (rate(vendor_cache_manager_keycloak_cache_realms_statistics_hits{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]) + rate(vendor_cache_manager_keycloak_cache_realms_statistics_misses{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]))",
     "legendFormat": "Realms cache hit ratio"
    },
    {
     "expr": "rate(vendor_cache_manager_keycloak_cache_users_statistics_hits{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]) / (rate(vendor_cache_manager_keycloak_cache_users_statistics_hits{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]) + rate(vendor_cache_manager_keycloak_cache_users_statistics_misses{namespace=\"${namespace}\", pod=\"$pod_name\", job=\"${namespace}/keycloak-otel\"}[2m]))",
     "legendFormat": "Users cache hit ratio"
    }
   ]
  },
  {
   "title": "$pod_name - Response time histogram",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (idelta(http_server_duration_bucket{http_route=~\"(/realms/{realm}/protocol/{protocol}/token|/realms/{realm}/protocol/{protocol}/auth|/realms/{realm}/protocol/{protocol}/logout|realms/{realm}/login-actions/authenticate)\", namespace=\"$namespace\", pod=\"$pod_name\"} [2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$pod_name - 99 quantile millis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{http_route=~\"(/realms/{realm}/protocol/{protocol}/token|/realms/{realm}/protocol/{protocol}/auth|/realms/{realm}/protocol/{protocol}/logout|realms/{realm}/login-actions/authenticate)\", namespace=\"$namespace\", pod=\"$pod_name\"}[2m])) by (le,http_route))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}