{
 "title": "Keycloak Infinispan board",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "local_cache",
    "query": "realms,users,authorization,keys"
   },
   {
    "name": "distributed_cache",
    "query": "sessions,authenticationSessions,offlineSessions,clientSessions,offlineClientSessions,loginFailures,actionTokens,work"
   }
  ]
 },
 "panels": [
  { "title": "Global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of ISPN nodes in cluster for each pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_cache_container_health_number_of_nodes{namespace=\"$namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Global cache hit ratio %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(vendor_cache_container_stats_hits{namespace=\"${namespace}\", job=~\"infinispan-admin|${namespace}/keycloak-metrics\"}[2m]) / (rate(vendor_cache_container_stats_hits{namespace=\"${namespace}\", job=~\"infinispan-admin|${namespace}/keycloak-metrics\"}[2m]) + rate(vendor_cache_container_stats_misses{namespace=\"${namespace}\", job=~\"infinispan-admin|${namespace}/keycloak-metrics\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JGroups thread pool stats",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "vendor_jgroups_ISPN_tcp_get_thread_pool_size{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} - pool size"
    },
    {
     "expr": "vendor_jgroups_ISPN_tcp_get_thread_pool_size_active{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} active threads"
    }
   ]
  },
  {
   "title": "JGroups average time blocked",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "vendor_jgroups_ISPN_ufc_get_average_time_blocked{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} UFC average time blocked"
    },
    {
     "expr": "vendor_jgroups_ISPN_mfc_get_average_time_blocked{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} MFC average time blocked"
    }
   ]
  },
  {
   "title": "Number of dropped JGroups messages",
   "type": "timeseries",
   "description": "RED (Random Early Drop) If the bundler queue starts to grows (i.e the socker.write() is unable to keep up with the number of messages to be sent) and gets closer to max size, this protocol will drop messages.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "vendor_jgroups_ISPN_tcp_get_num_rejected_msgs{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} - rejected msg by thread pool"
    },
    {
     "expr": "vendor_jgroups_ISPN_red_get_dropped_messages{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}",
     "legendFormat": "{{pod}} - RED dropped messages"
    }
   ]
  },
  {
   "title": "Percentage of dropped JGroups messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(vendor_jgroups_ISPN_red_get_dropped_messages{namespace=\"${namespace}\", job=~\"infinispan-admin|${namespace}/keycloak-metrics\"}[2m]) / rate(vendor_jgroups_ISPN_red_get_total_messages{namespace=\"${namespace}\", job=~\"infinispan-admin|${namespace}/keycloak-metrics\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of processed JGroups messages in last 2 minutes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "rate(vendor_jgroups_ISPN_red_get_total_messages{namespace=\"${namespace}\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Cache $distributed_cache stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "distributed_cache" },
  {
   "title": "# of entries in memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_approximate_entries_in_memory{cache=\"${distributed_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of put operations in last 2 minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(vendor_statistics_stores{cache=\"$distributed_cache\", job=~\"infinispan-admin|$namespace/keycloak-metrics\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_average_read_time_nanos{cache=\"${distributed_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average write",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_average_write_time_nanos{cache=\"${distributed_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "XSite requests to other DCs in last 2 minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (pod,other_dc_name) (rate(label_replace({__name__=~\"vendor_rpc_manager_number_xsite_requests_sent_to_.+\", job=\"infinispan-admin\", cache=\"$distributed_cache\", namespace=\"$namespace\"}, \"other_dc_name\", \"$1\", \"__name__\", \"vendor_rpc_manager_number_xsite_requests_sent_to_(.+)\")[2m:]))",
     "legendFormat": "{{pod}} -> {{other_dc_name}} - sent"
    },
    {
     "expr": "sum by (pod,other_dc_name) (rate(label_replace({__name__=~\"vendor_rpc_manager_number_xsite_requests_received_from_.+\", job=\"infinispan-admin\", cache=\"$distributed_cache\", namespace=\"$namespace\"}, \"other_dc_name\", \"$1\", \"__name__\", \"vendor_rpc_manager_number_xsite_requests_received_from_(.+)\")[2m:]))",
     "legendFormat": "{{pod}} <- {{other_dc_name}} - received"
    }
   ]
  },
  {
   "title": "Average xsite request duration to other DCs in ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod,other_dc_name) (label_replace({__name__=~\"vendor_rpc_manager_average_xsite_replication_time_to_.+\", job=\"infinispan-admin\", cache=\"$distributed_cache\", namespace=\"$namespace\"}, \"other_dc_name\", \"$1\", \"__name__\", \"vendor_rpc_manager_average_xsite_replication_time_to_(.+)\"))",
     "legendFormat": "{{pod}} -> {{other_dc_name}}"
    }
   ]
  },
  { "title": "Cache $local_cache stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 188 }, "repeat": "local_cache" },
  {
   "title": "# of entries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 189 },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_approximate_entries_in_memory{cache=\"${local_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Cache hit ratio %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(vendor_statistics_hits{cache=\"${local_cache}\", namespace=\"${namespace}\", job=\"${namespace}/keycloak-metrics\"}[2m]) / (rate(vendor_statistics_hits{cache=\"${local_cache}\", namespace=\"${namespace}\", job=\"${namespace}/keycloak-metrics\"}[2m]) + rate(vendor_statistics_misses{cache=\"${local_cache}\", namespace=\"${namespace}\", job=\"${namespace}/keycloak-metrics\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average read operation duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 10, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_average_read_time_nanos{cache=\"${local_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average write operation duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 14, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg without(instance,node,job,endpoint,otel_scope_name) (vendor_statistics_average_write_time_nanos{cache=\"${local_cache}\", namespace=\"${namespace}\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}