= Scenario AuthorizationCode
:description: Login a user with a username and password and exchange the authentication code.

{description}.

See xref:scenario-overview.adoc[] for a list of all scenarios.

== Steps of the scenario

. Open the login page.
. Login with username and password.
. Exchange the authentication code for a token.
. Logout.

See the source code at link:{github-files}/benchmark/src/main/scala/keycloak/scenario/authentication/AuthorizationCode.scala[AuthorizationCode.scala] for details.

== Running an example scenario

=== Prerequisites:

* Keycloak is running.
* Realm, user and client exist with the values listed on the CLI.
* The client needs to have client authentication enabled, which results in an OIDC type of confidential access type, as the confidential client secret is used in the authorization code exchange.
* This scenario doesn't need any service account roles set for the client.

See xref:preparing-keycloak.adoc[] for details how to automate this for the realm and the client.

=== Running the scenario

The following scenario runs with the default settings for 30 seconds.

See xref:configuration.adoc[] for additional CLI options.

[source,bash]
----
bin/kcb.sh \
  --scenario=keycloak.scenario.authentication.AuthorizationCode \
  --server-url=http://localhost:8080/ \
  --realm-name=realm-0 \
  --username=user-0 \
  --user-password=user-password-0 \
  --client-id=gatling \
  --client-secret=setup-for-benchmark \
  --client-redirect-uri=http://localhost:8081 \
  --log-http-on-failure
----

== Variants

To create offline sessions, set the parameter xref:configuration.adoc#scope[`--scope`] to a value including `offline_token`, for example, `openid profile offline_token`.

== Error messages

Invalid parameter: redirect_uri::
This could have the following reasons:
+
* The client with the given client ID doesn't exist in the given realm or has been mistyped.
+
_Remedy:_ Check that the client ID given on the command line or as the default exists in the given realm.

* Redirect URI doesn't match the redirect URI configured in the client.
+
_Remedy:_ Check that the redirect URI given on the command line or as the default matches the redirect URI in the client.

Invalid username or password::
This could be tested manually by trying to log in as the user on the account console at ++https://{keyloak-server}/realms/{realm}/account/++.
This could have the following reasons:
+
* The user with the given username doesn't exist.
+
_Remedy:_ Check that the user given on the command line or as the default exists in the given realm.

* The user has a different password.
+
_Remedy:_ Check that the user has the correct password set up.

== Further Reading

* xref:run/running-benchmark-cli.adoc[]
