# can't configure the storage of traces for badger via the helm chart
spec:
  template:
    spec:
      containers:
        - name: jaeger
          env:
            # https://www.jaegertracing.io/docs/1.35/cli/#jaeger-all-in-one-badger
            - name: SPAN_STORAGE_TYPE
              value: badger
            - name: BADGER_SPAN_STORE_TTL
              value: ${KB_RETENTION}
            - name: BADGER_EPHEMERAL
              value: "false"
          volumeMounts:
            - name: storage-jaeger
              mountPath: /go/bin/data
      volumes:
        - name: storage-jaeger
          persistentVolumeClaim:
            claimName: storage-jaeger
