# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml
provisionDataStore:
  cassandra: false
allInOne:
  enabled: true
  tag: 1.36.0
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 256m
      memory: 128Mi
storage:
  type: none
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
