# https://github.com/jaegertracing/helm-charts/blob/main/charts/jaeger/values.yaml
provisionDataStore:
  cassandra: false
allInOne:
  image:
    registry: "quay.io"
  enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 256m
      memory: 128Mi
  extraEnv:
    - name: "BADGER_SPAN_STORE_TTL"
      value: "24h"
storage:
  type: badger
  badger:
    ephemeral: false
    persistence:
       mountPath: /go/bin/data
       useExistingPvcName: "storage-jaeger"
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
