apiVersion: v1
kind: Secret
metadata:
  name: grafana-sa-secret
  annotations:
    kubernetes.io/service-account.name: grafana
# this then contains a non-expiring token which Grafana uses to access metrics in OpenShift
type: kubernetes.io/service-account-token
