name: Create Aurora Deployment
description: Create AWS Aurora DB Deployment

inputs:
  name:
    description: 'The name of the Aurora DB cluster to deploy'
    required: true
  region:
    description: 'The AWS region used to host the Aurora DB'
    required: true
  engineVersion:
    description: 'The Postgres engine version to use'
  instanceClass:
    description: 'Instance class for the Aurora DB'

runs:
  using: "composite"
  steps:
    - id: provision_aurora
      shell: bash
      run: ./aurora_create.sh
      working-directory: provision/aws/rds
      env:
        AURORA_CLUSTER: ${{ inputs.name }}
        AURORA_ENGINE_VERSION: ${{ inputs.engineVersion }}
        AURORA_INSTANCE_CLASS: ${{ inputs.instanceClass }}
        AWS_REGION: ${{ inputs.region }}
