name: Create Infinispan Deployment
description: Create Infinispan Deployment for running OpenShift project

inputs:
  cluster1:
    description: 'The first ROSA cluster'
    required: true
  namespace1:
    description: 'The namespace to install Infinispan in the first ROSA cluster.'
    required: true
  cluster2:
    description: 'The second ROSA cluster (optional)'
  namespace2:
    description: 'The namespace to install Infinispan in the second ROSA cluster.'


runs:
  using: "composite"
  steps:
    - id: install_infinispan
      shell: bash
      run: ./create_ispn_clusters.sh
      working-directory: provision/infinispan
      env:
        CLUSTER_1: ${{ inputs.cluster1 }}
        NS_1: ${{ inputs.namespace1 }}
        CLUSTER_2: ${{ inputs.cluster2 }}
        NS_2: ${{ inputs.namespace2 }}
