= AWS Route 53 as loadbalancer for ROSA
:description: This guide describes how to achieve automatic client-failover when a Keycloak deployment when a given site fails.

{description}

== Route 53 for Client Failover

To provide client failover, we can leverage https://aws.amazon.com/route53/[AWS Route 53]'s https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-failover-configuring.html[DNS failover] capabilities to automatically re-route traffic when the primary site is down.
A health check on AWS checks every 30 seconds if a site is responding, and the DNS as seen by the client will update accordingly.

This script generates a subdomain name, with three further host entries for our root domain `keycloak-benchmark.com`.

`primary.<generated-subdomain>.keycloak-benchmark.com`:: Subdomain for Keycloak site 1

`backup.<generated-subdomain>.keycloak-benchmark.com`:: Subdomain for Keycloak site 2

`client.<generated-subdomain>.keycloak-benchmark.com`:: Subdomain used by Keycloak clients, that will automatically fail over from 1 to 2 in the event of a failure.

Those DNS entries are registered with the OpenShift clusters so that they respond to requests to that host names.
After the setup, the Keycloak deployment is updated to use the new hostnames.

See below for the newly created elements (green) and the updated elements (yellow).

image::installation-openshift/route-53-configuration.dio.svg[]

== Setup new Route 53 failover

=== Prerequisites

* A Route 53 Hosted Zone for your domain
** https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/MigratingDNS.html[Existing Domain]
** https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring-new-domain.html[New Domain]

NOTE: A hosted zone already exists for keycloak-benchmark.com

=== Procedure

. Create two ROSA clusters
. Create subdomain records and health Checks
+
[source,bash]
----
PRIMARY_CLUSTER=<name-rosa-cluster> \
BACKUP_CLUSTER=<name-of-rosa_cluster> \
./provision/aws/route53/route53_create.sh
----
+
Note down the domain and URLs generated by the script for the following steps.
The generated part of the subdomain name allows for multiple Keycloak instances in the different clusters.
+
[source,bash]
----
Domain: <generated-subdomain>.keycloak-benchmark.com
Client Site URL: client.<generated-subdomain>.keycloak-benchmark.com
Primary Site URL: primary.<generated-subdomain>.keycloak-benchmark.com
Backup Site URL: backup.<generated-subdomain>.keycloak-benchmark.com
----

. Deploy Keycloak as normal, but with the following environment variables set.
.. Primary cluster:
+
[source,bash]
----
KC_HOSTNAME_OVERRIDE=client.<generated-subdomain>.keycloak-benchmark.com # Hostname used by clients
KC_HEALTH_HOSTNAME=primary.<generated-subdomain>.keycloak-benchmark.com # Hostname used by AWS health checks
----

.. Backup cluster:
+
[source,bash]
----
KC_HOSTNAME_OVERRIDE=client.<generated-subdomain>.keycloak-benchmark.com # Hostname used by clients
KC_HEALTH_HOSTNAME=backup.<generated-subdomain>.keycloak-benchmark.com # Hostname used by AWS health checks
----

=== Testing Failover

To test failover from primary to the backup site, do the following:

. Verify that `client.<generated-subdomain>.keycloak-benchmark.com` connects to primary.
+
[source,bash]
----
./provision/aws/route53/route53_test_primary_used.sh <generated-subdomain>.keycloak-benchmark.com; echo $?
----
+
The script returns `0` if the `client.` subdomain is pointing to the same IP as `primary.` subdomain.
+
NOTE: This script will fail if the `PRIMARY_CLUSTER` and `BACKUP_CLUSTER` are set to the same ROSA cluster.

. Login to the primary ROSA cluster and delete the `aws-health-route` Route from the keycloak namespace.

. Wait for about 30 seconds for the Health Checks to determine that `primary.<generated-subdomain>.keycloak-benchmark.com` is no longer healthy.
This can be confirmed by inspecting the health check https://us-east-1.console.aws.amazon.com/route53/healthchecks/home[in the AWS console].

. Execute the script from the first step and an exit code of `1` should be returned.

If the `aws-health-route` is recreated on the `PRIMARY_CLUSTER`, the health check will eventually pass and the `client.`
record will revert to routing requests to the primary cluster.

== Remove Route 53 Failover

To delete the generated subdomain including the health checks, run the following command.
If no subdomain is specified, all health checks are removed.

[source,bash]
----
SUBDOMAIN=<generated-subdomain> \
./provision/aws/route53/route53_delete.sh
----
