= Using CockroachDB single node storage
:description: The deployment of Keycloak can use a CockroachDB instance when using the new map storage.

{description}

As an alternative CockroachDB setup, there is also xref:./cockroach-operator.adoc[] which has more features and uses more resources.

== Enabling CockroachDB storage

Using a CockroachDB single node installation is available in Keycloak's new JPA map storage.
It can be enabled via the following settings in the `.env` file in the `provision/kubernetes` folder:

[source]
----
KC_DATABASE=cockroach-single
KC_STORAGE=jpa
----

See xref:customizing-deployment.adoc[] for a list of all configuration options.

include::partial$rerun-task-after-changes.adoc[]

The deployment adds a new CockroachDB pod to the minikube setup and removes all other storage pods that are no longer necessary.
Every time the pod is restarted, the database is cleared.

Keycloak connects to the CockroachDB database pod inside minikube and populates the DB schema.
The xref:util/sqlpad.adoc[SQL Pad] allows accessing the database via the browser.

image::storage/minikube-runtime-view-cockroach-single.dio.svg[]

== Verifying the setup

The automated script verifies that Keycloak starts up, which requires that CockroachDB start up first.
A user can test the setup by <<accessing-the-cockroachdb-console,accessing CockroachDB's console>>.

[#accessing-the-cockroachdb-console]
== Accessing the CockroachDB console

Assuming the command `minikube ip` returned `192.168.39.39`, the console is available on \http://cockroach.192.168.39.39.nip.io.

The username is `keycloak`, password is `pass`.

include::partial$minikube-ip-change.adoc[]

== Connecting a local application to CockroachDB

CockroachDB's database port is also available as a node port so that it can be accessed from a local application.
Assuming the command `minikube ip` returned `192.168.39.39`, the JDBC URL is `jdbc:postgres://192.168.39.39:30010/keycloak?sslmode=disable`.

include::partial$minikube-ip-change.adoc[]

It can be used, for example, to connect the developer's IDE to the database.

The connection details: Port is always `30010`, username is `keycloak`, password is `pass`, database name is `keycloak`.

include::partial$port-offset-note.adoc[]

== Metrics and Dashboards for CockroachDB

Metrics from the CockroachDB are available in Prometheus, and dashboards are available in Grafana.
They are named "`CDRB Console: SQL`", "`CDRB Console: Runtime`" and "`CDRB Console: Storage`".
The dashboards have been taken from https://www.cockroachlabs.com/docs/stable/monitor-cockroachdb-with-prometheus.html[the CockroachDB manual] and adapted for the Job name.

To see all metrics, query Prometheus for `+{job="keycloak/cockroach-metrics"}+`.

== Known issues for the CockroachDB setup

Users of this setup should be aware of the following known issues.

include::partial$cockroach-retry.adoc[leveloffset=+2]
