= Using External Infinispan storage with new store
:description: The deployment of Keycloak can use an external Infinispan instance when deployed with the new map storage.

{description}

This is different from the legacy setup where Keycloak used an embedded Infinispan instance.

== Enabling Infinispan

Using an external Infinispan instance is available in Keycloak's new Hot Rod map storage.
It can be enabled via the following settings in the `.env` file in the `provision/kubernetes` folder:

[source]
----
KC_DATABASE=infinispan
KC_STORAGE=hotrod
----

See xref:customizing-deployment.adoc[] for a list of all configuration options.

include::partial$rerun-task-after-changes.adoc[]

The deployment adds a new Infinispan pod to the minikube setup and removes all other storage pods that are no longer necessary.
Every time the pod is restarted, the database is cleared.

Keycloak connects to the new Infinispan pod inside minikube, and <<accessing-the-infinispan-console,Infinispan's web console is available via the local browser>>.

image::storage/minikube-runtime-view-infinispan.dio.svg[]

== Verifying the setup

The automated script verifies that Keycloak starts up, which requires that Infinispan start up first.
A user can test the setup by <<accessing-the-infinispan-console,accessing Infinispan's console>>.

[#accessing-the-infinispan-console]
== Accessing the Infinispan console

Assuming the command `minikube ip` returned `192.168.39.39`, the console is available on \http://infinispan.192.168.39.39.nip.io.

include::partial$minikube-ip-change.adoc[]

The username is `admin` with the password `admin`.

== Connecting a local application to Infinispan

Infinispan's port is also available as a node port so that it can be accessed from a local application.
Assuming the command `minikube ip` returned `192.168.39.39`, point the local instance to `192.168.39.39:30011`.

include::partial$minikube-ip-change.adoc[]

include::partial$port-offset-note.adoc[]

It can be used, for example, with Infinispan's command line client.

The username is `admin` with the password `admin`.

[WARNING]
====
The infinispan instance running inside the pod advertises its pod IP address to the caller that is not accessible from the outside of minikube.

Due to this, accessing Infinispan from an application running outside minikube most likely fails until the required but yet unknown parameters are passed to either the application or the pod.
====



