= Using mixed PostgreSQL and Infinispan storage
:description: The deployment of Keycloak can use a PostgreSQL database and an external infinispan Instance when deployed with the new map storage.

{description}

This mixed setup mirrors what the Legacy store: auth sessions, user sessions, login failures, and single use objects are stored via the Hot Rod protocol in an Infinispan instance, all other entities are stored via JPA in a PostgreSQL instance.
All stores use the new map store implementation.

== Enabling Infinispan

Using an external Infinispan instance is available in Keycloak's new Hot Rod map storage.
It can be enabled via the following settings in the `.env` file in the `provision/kubernetes` folder:

[source]
----
KC_DATABASE=postgres+infinispan
KC_STORAGE=jpa+hotrod
----

See xref:customizing-deployment.adoc[] for a list of all configuration options.

include::partial$rerun-task-after-changes.adoc[]

The deployment adds a new Infinispan pod to the minikube setup and removes all other storage pods that are no longer necessary.
Every time the pod is restarted, the database is cleared.

== Further reading

To verify the setup and to access the consoles for PostgreSQL and Infinispan, visit the respective pages:

* xref:./postgres.adoc[]
* xref:./infinispan.adoc[]


