= {project_name} cluster deployment
:description: This document contains details of the metrics to monitor your {project_name} deployment's performance.
:jgrp_application: {project_name}
:clustered_caches: true

{description}

The deployment described in this document is for single-site deployments.
In this architecture, {project_name} nodes creates cluster between themselves, used by the {ispn} clustered caches.

If an external {jdgserver_name} is used, check xref:./keycloak_with_external_infinispan.adoc[] guide.

include::partial$/running/metrics/kc_enable_metrics.adoc[leveloffset=+1]
include::partial$/running/metrics/kc_http_metrics.adoc[leveloffset=+1]

== Clustering and Network

Multiple {project_name} nodes allows to distribute the load among them, but it requires communication between the nodes.
This section describes the useful metrics to monitor the network between {project_name} nodes and possible faults.

include::partial$/running/metrics/jgrp_metrics.adoc[leveloffset=+1]

== {ispn} Caches

{project_name} caches data in embedded {ispn} caches. The metrics in this section help monitoring the caching health and the cluster replication.

include::partial$/running/metrics/ispn_metrics.adoc[leveloffset=+1]
