= {project_name} cluster deployment
:description: This document contains details of the metrics to monitor your {project_name} deployment's performance.
:jgrp_application: {project_name}
:clustered_caches: true

{description}

The deployment described in this document is for single-site deployments.
In this architecture, {project_name} nodes leverage {ispn} embedded clustered caches to form a cluster.

If an external {jdgserver_name} is used, check xref:./keycloak_with_external_infinispan.adoc[] guide.

include::partial$/running/metrics/kc_enable_metrics.adoc[leveloffset=+1]
include::partial$/running/metrics/kc_http_metrics.adoc[leveloffset=+1]

== Clustering and Network

Deploying multiple {project_name} nodes allows the load to be distributed amongst them, but this requires communication between the nodes.
This section describes metrics that are useful for monitoring the communication between {project_name} in order to identify possible faults.

include::partial$/running/metrics/jgrp_metrics.adoc[leveloffset=+1]

== {ispn} Caches

{project_name} caches data in embedded {ispn} caches. The metrics in this section help to monitor the caching health and the cluster replication.

include::partial$/running/metrics/ispn_metrics.adoc[leveloffset=+1]
