---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: grafana
  name: grafana-ingress
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: jaeger-query
      port:
        number: 16686
  rules:
    - host: jaeger.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: jaeger-query
                port:
                  number: 16686
            path: /
            pathType: ImplementationSpecific
