kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-jaeger
  namespace: monitoring
  labels:
    app: jaeger
    release: jaeger
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
