name: Create EC2 instances
description: Creates EC2 instances

inputs:
  region:
    description: 'The AWS region used to host the EC2 instances.'
    required: true
  clusterId:
    description: 'The unique ID for the EC2 instances cluster.'
    default: ${{ github.run_id }}

runs:
  using: composite
  steps:
    - id: aws-ec2-requirements-install
      name: Install the required Ansible AWS collections.
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        ./aws_ec2.sh requirements
        pipx inject ansible-core boto3 botocore
      working-directory: ansible

    - id: create-ec2-instances
      shell: bash
      run: |
        ./aws_ec2.sh create ${{ inputs.region }}
      working-directory: ansible
      env:
        CLUSTER_ID: ${{ inputs.clusterId }}
