= Error messages and remedies for Kubernetes
:navtitle: Error messages and remedies
:description: This describes common error messages and their remedies when running the Keycloak Benchmark suite on Kubernetes.

{description}

[#keycloak-message-error-failed-to-obtain-jdbc-connection]
== Keycloak message `ERROR: Failed to obtain JDBC connection`

Context::
This error message can appear when running Keycloak with a relational database like PostgreSQL or CockroachDB.
+
Similar other error messages:
+
--
* "`Unable to acquire JDBC Connection`"
* "`Sorry, acquisition timeout!`"
--
+
This might happen during the startup and then the startup fails.
It might also happen during a load test when Keycloak creates new database connections.

Cause::
The database is either not started, or the number of database connections is exhausted in the current setup.

Remedy::
* Ensure that the database is running.
* Ensure that the database didn't restart, for example, due to an out-of-memory problem.
* Ensure that the number of DB connections in total doesn't exceed the maximum number of connections of the database.
See xref:customizing-deployment.adoc#KC_DB_POOL_INITIAL_SIZE[the Keycloak deployment configuration options `KC_DB_*`] for details.
* Ensure that Keycloak doesn't try to use more connections than configured as maximum numbers of connections.

Caution::
* Under high load, the number of database connections is usually the constraint of the system.
Having Keycloak running into a "`Sorry, acquisition timeout`" and returning an HTTP 5xx code to the caller is a sensible load shedding mechanism.
See xref:load-behavior.adoc[] for details.

[[retry-serializable]]
== Keycloak message `RETRY_SERIALIZABLE`

Full message::
org.postgresql.util.PSQLException, ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - failed preemptive refresh due to a conflict: intent on key /Table/137/... See: \https://www.cockroachlabs.com/docs/v22.1/transaction-retry-error-reference.html#retry_serializable

Context::
This error message can appear when running Keycloak with CockroachDB, both xref:storage/cockroach-single.adoc[single node] or xref:storage/cockroach-operator.adoc[multi node with the operator].
+
This might happen during the load test while Keycloak processes requests.

Cause::
Some transactions are not fully serializable, therefore, the database rolls back the transaction and asks the caller to repeat the request.

Remedy::
* Analyze the request/URL where this happens by looking at the log, and discuss this with engineers.
* Use the following SQL to determine the table which is causing the problems, which would by `137` in the example given above:
+
[source,sql]
----
SELECT DISTINCT ti.descriptor_name as table_name, us.table_id
  FROM  crdb_internal.index_usage_statistics us, crdb_internal.table_indexes ti
  WHERE us.table_id = ti.descriptor_id ORDER BY us.table_id ASC;
----
