= Installing on OpenShift
:page-aliases: openshift.adoc
:description: Deploy Keycloak on OpenShift with a setup similar to the minikube environment.

{description}

While minikube is the primary target for this setup, this tracks the progress on how to use it with an OpenShift environment, see <<supported-functionality>>.

Access to OpenShift with the `cluster-admin` role is required to be able to install custom resource definitions.

WARNING: OpenShift must not be accessible from the Internet, as this setup opens node ports and URLs that are not properly secured by good passwords and transport encryption.

== Prerequisites

* xref:prerequisite/prerequisite-openshift.adoc[OpenShift]
* xref:prerequisite/prerequisite-helm.adoc[Helm]
* xref:prerequisite/prerequisite-kubectl.adoc[kubectl]
* xref:prerequisite/prerequisite-task.adoc[task]
* xref:prerequisite/prerequisite-yq.adoc[yq]
* xref:prerequisite/prerequisite-java.adoc[Java]

Verify that the setup works using `oc cluster-info`.

[[supported-functionality]]
== Supported functionality

At the moment, the following is known not to work on OpenShift:

sqlpad:: Container requires a root user.
cryostat:: OpenShift instance needs to have persistent storage enabled for this to work.
monitoring:: The OpenShift only provides Grafana for monitoring. Jaeger and Graphite are not implemented yet.

== Installing Keycloak on OpenShift

. Check out the Git repository from https://github.com/keycloak/keycloak-benchmark/.

. Change to the folder `provision/openshift`.

. Edit the configuration file `.env` with the following settings:
+
[source,subs=+quotes]
----
KC_HOSTNAME_SUFFIX=apps.**<domain name>**
----
+
`KC_HOSTNAME_SUFFIX` should be the hostname that you also see in the web browser when opening the OpenShift console.

. Run the `task` command to provision all containers on OpenShift.

=== Verifying the installation

Run the following script to check if all services are running and receive a list of available URLs:

[source,shell]
----
./isup.sh
----

== Installation Grafana monitoring

To install Grafana with a pre-configured dashboard, perform the following step:

. Run the `task monitoring` command

=== Verifying the installation

The Grafana dashboard is then available on:

[source,subs=+quotes]
----
http://grafana.apps.**<domain name>**
----

NOTE: This is a shared resource for all users using the OpenShift cluster.
While the next section describes how to install multiple Keycloaks in different namespaces, this doesn't apply to the Grafana instance.

[[sharing-cluster-with-multiple-users]]
== Sharing one Openshift cluster with other users

The following options are necessary for customizing Keycloak deployment in a way that it can be used concurrently by multiple users within one Openshift cluster.

`xref:customizing-deployment.adoc#KC_NAMESPACE_PREFIX[KC_NAMESPACE_PREFIX]`:: Allows customizing the namespace name.
The resulting namespace will be `++${KC_NAMESPACE_PREFIX}++keycloak`.
By default, the namespace prefix is set to `$(whoami)-`, but it can be customized in `.env` file.

`xref:customizing-deployment.adoc#KC_PORT_OFFSET[KC_PORT_OFFSET]`:: Keycloak deployment contains several services that are exposed via NodePort.
By default, the port offset is set to `0`.
When more users use Keycloak benchmark with the same port offset the task execution will fail with the following message: `Invalid value: 3XXXX: provided port is already allocated`, in that case choose different port offset value in the `.env` file.

