= Installing on OpenShift
:page-aliases: openshift.adoc
:description: Deploy Keycloak on OpenShift with a setup similar to the minikube environment.

{description}

While minikube is the primary target for this setup, this tracks the progress on how to use it with an OpenShift environment, see <<supported-functionality>>.

Access to OpenShift with the `cluster-admin` role is required to be able to install custom resource definitions.

WARNING: OpenShift must not be accessible from the Internet, as this setup opens node ports and URLs that are not properly secured by good passwords and transport encryption.

== Prerequisites

* xref:prerequisite/prerequisite-openshift.adoc[OpenShift]
* xref:prerequisite/prerequisite-helm.adoc[Helm]
* xref:prerequisite/prerequisite-kubectl.adoc[kubectl]
* xref:prerequisite/prerequisite-task.adoc[task]
* xref:prerequisite/prerequisite-yq.adoc[yq]
* xref:prerequisite/prerequisite-java.adoc[Java 17]

Verify that the setup works using `oc cluster-info`.

[[supported-functionality]]
== Supported functionality

At the moment, the following is known not to work on OpenShift:

sqlpad:: Container requires a root user.
monitoring:: The OpenShift only provides Grafana, OpenTelemetry and Jaeger for monitoring.
Graphite is not implemented yet.

Cryostat depends on the Cryostat Operator to be installed, which is the default for the installation scripts provided by xref:prerequisite/prerequisite-rosa.adoc[].

== Installing Keycloak on OpenShift

. Check out the Git repository from https://github.com/keycloak/keycloak-benchmark/.

. Change to the folder `provision/openshift`.

. Run the `task` command to provision all containers on OpenShift.

=== Verifying the installation

Run the following script to check if all services are running and receive a list of available URLs:

[source,shell]
----
./isup.sh
----

== Installation Grafana monitoring

To install Grafana with a pre-configured dashboard, perform the following step:

. Run the `task monitoring` command

=== Verifying the installation

The Grafana dashboard is then available on:

[source,subs=+quotes]
----
http://grafana.apps.**<domain name>**
----

NOTE: This is a shared resource for all users using the OpenShift cluster.
While the next section describes how to install multiple Keycloaks in different namespaces, this doesn't apply to the Grafana instance.

== OpenShift Logging
Openshift logging is enabled by default. All application and infrastructure pod logs are stored in a non-replicated
ElasticSearch instance in the `openshift-logging` namespace. Logs can be queried in the Kibana UI, which can be accessed
via the "Application Launcher" -> "Logging" link in the Openshift UI.

On initial login to Kibana it's first necessary for an "app*" index to be created in order to be able to query logs. See the
https://docs.openshift.com/container-platform/4.13/logging/cluster-logging-visualizer.html[Openshift docs] for more details.

[[sharing-cluster-with-multiple-users]]
== Sharing one OpenShift cluster with other users

The following options are necessary for customizing Keycloak deployment in a way that it can be used concurrently by multiple users within one OpenShift cluster.

`xref:customizing-deployment.adoc#KC_NAMESPACE_PREFIX[KC_NAMESPACE_PREFIX]`:: Allows customizing the namespace name.
The resulting namespace will be `++${KC_NAMESPACE_PREFIX}++keycloak`.
By default, the namespace prefix is set to `$(whoami)-`, but it can be customized in `.env` file.
