= Dataset Guide for Keycloak Benchmark

Dataset provider is useful to populate target Keycloak/RHSSO server with many objects in test enviroment.

The approach of using Keycloak Admin REST API directly is slow in many environments, and hence this approach is used to fill the data quickly.

The dataset provider should *never* be installed in a production environment, as it allows creating and deleting entities without authentication.

For example:

Populate a Keycloak realm with many users::
This is useful to run performance test with many concurrent user logins and use different users for each login.

Populate a realm with many clients::
This is useful for testing service account logins and others.

Populate your Keycloak server with many realms::
Each realm will be filled with a specified number of roles, clients, groups and users, so this endpoint might be sufficient for most of the performance testing use-cases.

== Next steps

Learn more on how to install it or what its API has to offer:

* xref:installing-provider.adoc[]
* xref:using-provider.adoc[]:
Explore the API offerings of this provider.
