= Generating datasets
:description: This describes how to use the dataset provider and its API to generate datasets for load testing.

{description}

include::partial$warning-not-in-production.adoc[]

== Prerequisites

* xref:installing-provider.adoc[]

When using Quarkus or the minikube installation, all URLs start with `/realms/master`.
For the Wildfly distribution, the URL starts with `/auth/realms/master`.

== Using the dataset provider

=== Scripted usage

This script contains a subset of the operations described in the next sections around realms, users and clients.

Run the following command to receive a help description:

----
./dataset_import.sh -h
----

You will see these options:

----
Dataset import to the local minikube Keycloak application.
Usage:
1) create realm/s with clients, users and password hash iterations - run it with or without arguments: -r | --create-realms '10 100 100 20000'
2) create clients in specific realm: -c | --create-clients '100 realm-0'
3) create users in specific realm: -u | --create-users '100 realm-0'
4) create events in specific realm: -e | --create-events '100 realm-0'
5) create offline sessions in specific realm: -o | --create-offline-sessions '100 realm-0'
6) delete specific realm/s with prefix -d | --delete-realms realm
7) dataset provider status -s | --status
8) dataset import script usage -h | --help
----

Example of creating 10 new realms:

----
./dataset_import.sh -r 10
----

=== Create many realms

You need to call this HTTP REST requests.
This request is useful for create 10 realms.
Each realm will contain specified amount of roles, clients, groups and users:

----
.../realms/master/dataset/create-realms?count=10
----

=== Create many clients

This is request to create 100 new clients in the realm `realm-5` . Each client will have service account enabled and secret like «client_id»-secret (For example `client-156-secret` in case of the client `client-156`):

----
.../realms/master/dataset/create-clients?count=200&realm-name=realm-5
----

You can also configure the access-type (`bearer-only`, `confidential` or `public`) and whether the client should be a service-account-client with these two parameters:

----
...&client-access-type=bearer-only&service-account-client=false
----

=== Create many users

This is request to create 500 new users in the `realm-5`.
Each user will have specified amount of roles, client roles and groups, which were already created by `create-realms` endpoint.
Each user will have password like «Username»-password . For example `user-156` will have password like
`user-156-password` :

----
.../realms/master/dataset/create-users?count=1000&realm-name=realm-5
----

=== Create many events

This is request to create 10M new events in the available realms with prefix `realm-`.
For example if we have 100 realms like `realm-0`, `realm-1`, ... `realm-99`, it will create 10M events randomly in them

----
.../realms/master/dataset/create-events?count=10000000
----

=== Create many offline sessions

This is request to create 10M new offline sessions in the available realms with prefix `realm-`.
For example if we have 100 realms like `realm-0`, `realm-1`, … `realm-99`, it will create 10M events randomly in them

----
.../realms/master/dataset/create-offline-sessions?count=10000000
----

=== Remove many realms

To remove all realms with the default realm prefix `realm`

----
.../realms/master/dataset/remove-realms?remove-all=true
----

You can use `realm-prefix` to change the default realm prefix.
You can use parameters to remove all realms for example just from `foorealm5` to `foorealm15`

----
.../realms/master/dataset/remove-realms?realm-prefix=foorealm&first-to-remove=5&last-to-remove=15
----

=== Change default parameters

For change the parameters, take a look at link:{github-files}/dataset/src/main/java/org/keycloak/benchmark/dataset/config/DatasetConfig.java[DataSetConfig class]
to see available parameters and default values and which endpoint the particular parameter is applicable.
For example to create realms with prefix `foo` and with just 1000 hash iterations used for the password policy, you can use these parameters:

----
.../realms/master/dataset/create-realms?count=10&realm-prefix=foo&password-hash-iterations=1000
----

The configuration is written to the server log when HTTP endpoint is triggered, so you can monitor the progress and what parameters were effectively applied.

Note that creation of new objects will automatically start from the next available index.
For example when you trigger endpoint above for creation many clients and you already had 230 clients in your DB (`client-0`, `client-1`, .. `client-229`), then your HTTP request will start creating clients from `client-230` .

=== Check if the task is still running

Call the following URL using the `GET` method:

----
.../realms/master/dataset/status
----

If there is a task still running, it returns information like the following:

----
{"status":"Task in progress","task-id":{"startTimeMs":"1662115169043","message":"Creation of 1 realms from realm-6 to realm-6"}}
----

If there is no task running, it returns information like the following:

----
{"status":"No task in progress. New task can be started"}
----

=== Check the result of the last completed task

Call the following URL using the `GET` method:

----
.../realms/master/dataset/status-completed
----

If there is a task still running, it returns information like the following:

----
{"status":"previous task completed","task":{"success":"true","startTimeMs":"1662115169043","message":"Creation of 1 realms from realm-1 to realm-1","endTimeMs":"1662115173323"}}
----

If there is no completed task, it returns this information with status code 404:

----
{"status":"No completed task"}
----

=== Clear the result of the last completed task

Call the following URL using the `DELETE` method:

----
.../realms/master/dataset/status-completed
----

=== Check the last items of a particular object

To see the last created realm index

----
.../realms/master/dataset/last-realm
----

To see the last created client in given realm

----
.../realms/master/dataset/last-client?realm-name=realm5
----

To see the last created user in a given realm

----
.../realms/master/dataset/last-user?realm-name=realm5
----

== Further reading

* xref:clearing-caches.adoc[]
