{{ if .Values.cryostat }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cryostat
  namespace: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cryostat
subjects:
- kind: ServiceAccount
  name: cryostat
  namespace: keycloak
{{end}}
