{{ if .Values.cryostat }}
apiVersion: v1
data:
  GF_SECURITY_ADMIN_PASSWORD: Y3J5b3N0YXQ= # cryostat
  GF_SECURITY_ADMIN_USER: YWRtaW4= # admin
kind: Secret
metadata:
  name: cryostat-grafana-basic
  namespace: keycloak
type: Opaque
{{end}}
