{{ if .Values.cryostat }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cryostat
    component: cryostat
  name: cryostat-jfr
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: jfr-jmx
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: cryostat
  sessionAffinity: None
  type: ClusterIP
{{end}}
