{{ if and (.Values.cryostat) (not (eq .Values.environment "openshift")) }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cryostat
    component: cryostat
  name: cryostat
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: export
    port: 8181
    protocol: TCP
    targetPort: 8181
  selector:
    app: cryostat
  sessionAffinity: None
  type: ClusterIP
{{end}}
