{{ if and (.Values.cryostat) (not (eq .Values.environment "openshift")) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cryostat
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - replicationcontrollers
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - get
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
{{end}}
