{{ if and (.Values.cryostat) (not (eq .Values.environment "openshift")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cryostat
  name: cryostat
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard
  volumeMode: Filesystem
{{end}}
