name: Java CI with Maven

on:
  schedule:
    # run weekly to ensure to catch build being broken against upstream
    - cron: "0 7 * * 1"
  push:
    # dependabot will create both branches and pull request
    # only run on pull requests to avoid running twice and creating a release draft
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'provision/**'
      - 'antora/**'
      - 'doc/**'
      - '.github/workflows/*.yml'
      - '!.github/workflows/build.yml'
  pull_request:
    paths-ignore:
      - 'provision/**'
      - 'antora/**'
      - 'doc/**'
      - '.github/workflows/*.yml'
      - '!.github/workflows/build.yml'

concurrency:
  # Only run once for the latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: |
            .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-wrapper-
      - name: Build with Maven
        run: |
          ./mvnw -B clean verify
