name: Publishing Documentation Site

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs-pages.yml'
      - 'antora/**'
      - 'doc/**'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # allow publishing of github pages
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: actions/cache@v2
        with:
          path: 'antora/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('antora/yarn.lock') }}
      - name: Build docs
        working-directory: antora
        run: ./build.sh
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: antora/_site/keycloak-benchmark

  github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref_name == 'main' && github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
