name: Infinispan - Delete Deployment

on:
  workflow_dispatch:
    inputs:
      clusterName1:
        description: 'Name of the first ROSA cluster'
        type: string
        required: true
      namespace1:
        description: 'Namespace to deploy Infinispan in the first ROSA cluster'
        type: string
        required: true
      clusterName2:
        description: 'Name of the second ROSA cluster'
        type: string
        required: false
      namespace2:
        description: 'Namespace to deploy Infinispan in the second ROSA cluster'
        type: string
        required: false

jobs:
  prepare:
    name: Delete Infinispan deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}
      - name: Create Infinispan deployment
        uses: ./.github/actions/infinispan-delete-deployment
        with:
          cluster1: ${{ inputs.clusterName1 }}
          namespace1: ${{ inputs.namespace1 }}
          cluster2: ${{ inputs.clusterName2 }}
          namespace2: ${{ inputs.namespace2 }}
