name: Infinispan - Cross-site in Two Clusters Deployment

on:
  workflow_dispatch:
    inputs:
      clusterName1:
        description: 'Name of the first ROSA cluster'
        type: string
        required: true
      namespace1:
        description: 'Namespace to deploy Infinispan in the first ROSA cluster'
        type: string
        required: true
      clusterName2:
        description: 'Name of the second ROSA cluster'
        type: string
        required: true
      namespace2:
        description: 'Namespace to deploy Infinispan in the second ROSA cluster'
        type: string
        required: true

jobs:
  prepare:
    name: Create Infinispan deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}
      - name: Setup Go Task
        uses: ./.github/actions/task-setup
      - name: Create Infinispan deployment
        working-directory: provision/infinispan
        run: task crossdc
        env:
          ROSA_CLUSTER_NAME_1: "${{ inputs.clusterName1 }}"
          ROSA_CLUSTER_NAME_2: "${{ inputs.clusterName2 }}"
          OC_NAMESPACE_1: "${{ inputs.namespace1 }}"
          OC_NAMESPACE_2: "${{ inputs.namespace2 }}"
