name: Multi-AZ Clusters - Single-Site - Undeploy

on:
  workflow_dispatch:
    inputs:
      clusterPrefix:
        description: 'The prefix to be used when cleaning the clusters'
        type: string
      region:
        description: 'The AWS region to create both clusters in. Defaults to "vars.AWS_DEFAULT_REGION" if omitted.'
        type: string
  workflow_call:
    inputs:
      clusterPrefix:
        description: 'The prefix to be used when cleaning the clusters'
        type: string
      region:
        description: 'The AWS region to create both clusters in. Defaults to "vars.AWS_DEFAULT_REGION" if omitted.'
        type: string

env:
  CLUSTER_PREFIX: ${{ inputs.clusterPrefix || format('gh-{0}', github.repository_owner) }}
  REGION: ${{ github.event.inputs.region || vars.AWS_DEFAULT_REGION }}

jobs:
  single-site-undeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}

      - name: Setup Go Task
        uses: ./.github/actions/task-setup

      - name: Undeploy Single-Site Keycloak
        working-directory: provision/rosa-cross-dc
        run: |
          task undeploy-single-site
        env:
          KUBECONFIG: ../aws/kubeconfig
          ROSA_CLUSTER_NAME: ${{ inputs.clusterPrefix }}-a

