name: Multi-AZ Clusters - Delete

on:
  workflow_dispatch:
    inputs:
      clusterPrefix:
        description: 'The prefix to be used when creating the clusters'
        type: string
      region:
        description: 'The AWS region to create both clusters in. Defaults to "vars.AWS_DEFAULT_REGION" if omitted.'
        type: string

env:
  CLUSTER_PREFIX: ${{ inputs.clusterPrefix || format('gh-{0}', github.repository_owner) }}
  REGION: ${{ github.event.inputs.region || vars.AWS_DEFAULT_REGION }}

jobs:
  route53:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}

      - name: Login to OpenShift cluster
        uses: ./.github/actions/oc-keycloak-login
        with:
          clusterName: ${{ inputs.clusterPrefix }}-a

      - name: Get Keycloak Domain
        uses: ./.github/actions/get-keycloak-url
        with:
          project: runner-keycloak

      - name: Delete Route53 Records
        run: |
          SUBDOMAIN=$(echo $KEYCLOAK_URL | grep -oP '(?<=client.).*?(?=.keycloak-benchmark.com)')
          ./provision/aws/route53/route53_delete.sh

  cluster1:
    uses: ./.github/workflows/rosa-cluster-delete.yml
    with:
      clusterName: ${{ inputs.clusterPrefix }}-a
      deleteAll: no
    secrets: inherit

  cluster2:
    uses: ./.github/workflows/rosa-cluster-delete.yml
    with:
      clusterName: ${{ inputs.clusterPrefix }}-b
      deleteAll: no
    secrets: inherit

  delete-aurora:
    needs:
      - cluster1
      - cluster2
    uses: ./.github/workflows/aurora-cluster-delete.yml
    with:
      name: ${{ env.CLUSTER_PREFIX }}
      region: ${{ env.REGION }}
    secrets: inherit
