name: ROSA Scheduled Run

on:
  schedule:
    - cron: '0 5 * * 1' # Runs At 05:00 UTC on Monday.
  workflow_dispatch:

# env:
#   CLUSTER_PREFIX: gh-keycloak

jobs:
  rosa-multi-az-clusters-run-tests:
    name: Multi-AZ Clusters - Run Tests
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
    uses: ./.github/workflows/rosa-multi-az-clusters-run-tests.yml
    secrets: inherit

  rosa-stretched-cluster:
    name: Stretched Cluster - Create
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
    uses: ./.github/workflows/rosa-stretched-cluster.yml
    secrets: inherit

  rosa-stretched-cluster-benchmark:
    name: Stretched Cluster - Benchmark
    needs:
      - rosa-stretched-cluster
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
    uses: ./.github/workflows/rosa-single-cluster-benchmark.yml
    with:
      clusterName: ${{ format('gh-{0}-az', github.repository_owner) }}
      outputArchiveSuffix: "stretched-cluster"
      clusterIdSuffix: "_sc"
