name: ROSA Scheduled Delete

on:
  schedule:
    - cron: '0 19 * * *' # Runs every day at 7 PM UTC.

jobs:

  checkout:
    name: ROSA Scheduled Delete cluster(s)
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run -R keycloak/keycloak-benchmark rosa-cluster-delete.yml -f deleteAll='yes'
        if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
