name: Multi-AZ Clusters - Create ROSA Clusters

on:
  workflow_dispatch:
    inputs:
      clusterPrefix:
        description: 'The prefix to be used when creating the clusters'
        type: string
      region:
        description: 'The AWS region to create both clusters in. Defaults to "vars.AWS_DEFAULT_REGION" if omitted.'
        type: string
      computeMachineType:
        description: 'Instance type for the compute nodes'
        default: 'c7g.2xlarge'
        type: string
  workflow_call:
    inputs:
      clusterPrefix:
        description: 'The prefix to be used when creating the clusters'
        type: string
      region:
        description: 'The AWS region to create both clusters in. Defaults to "vars.AWS_DEFAULT_REGION" if omitted.'
        type: string
      infinispan_operator_olm_catalog_source:
        type: string
        default: community-operators
      infinispan_operator_olm_name:
        type: string
        default: infinispan
      computeMachineType:
        description: 'Instance type for the compute nodes'
        default: 'c7g.2xlarge'
        type: string

env:
  CLUSTER_PREFIX: ${{ inputs.clusterPrefix || format('gh-{0}', github.repository_owner) }}
  REGION: ${{ inputs.region || vars.AWS_DEFAULT_REGION }}
  
jobs:
  # Workaround required for passing env variables to reusable workflow declarations as ${{ env.* }} is not available
  meta:
    runs-on: ubuntu-latest
    outputs:
      clusterPrefix: ${{ env.CLUSTER_PREFIX }}
      region: ${{ env.REGION }}
      cidrA: ${{ steps.cidr.outputs.CIDR_A }}
      cidrB: ${{ steps.cidr.outputs.CIDR_B }}
    concurrency:
      group: multi-az-meta
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}

      - name: Calculate Cluster CIDR
        id: cidr
        run: |
          set -x
          CIDRS=$(./rosa_machine_cidr.sh)
          echo "CIDR_A=$(echo ${CIDRS} | jq -r .cidr_a )" >> ${GITHUB_OUTPUT}
          echo "CIDR_B=$(echo ${CIDRS} | jq -r .cidr_b )" >> ${GITHUB_OUTPUT}
        working-directory: provision/aws
        env:
          CLUSTER_PREFIX: ${{ env.CLUSTER_PREFIX }}

  cluster:
    needs: meta
    strategy:
      matrix:
        availabilityZone: [ a, b ]
      fail-fast: false
    uses: ./.github/workflows/rosa-cluster-create.yml
    with:
      cidr: ${{ matrix.availabilityZone == 'a' && needs.meta.outputs.cidrA || needs.meta.outputs.cidrB }}
      clusterName: ${{ needs.meta.outputs.clusterPrefix }}-${{ matrix.availabilityZone }}
      region: ${{ needs.meta.outputs.region }}
      availabilityZones: ${{ needs.meta.outputs.region }}${{ matrix.availabilityZone }}
      infinispan_operator_olm_catalog_source: ${{ inputs.infinispan_operator_olm_catalog_source }}
      infinispan_operator_olm_name: ${{ inputs.infinispan_operator_olm_name }}
    secrets: inherit

