name: ROSA Daily Scheduled Run

on:
  schedule:
    - cron: '0 5 * * 1-5' # Runs At 05:00 UTC on every day-of-week from Monday through Friday.
  workflow_dispatch:

# env:
#   CLUSTER_PREFIX: gh-keycloak

jobs:
  rosa-multi-az-clusters-run-tests:
    name: Multi-AZ Clusters - Run Tests
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
    uses: ./.github/workflows/rosa-multi-az-clusters-run-tests.yml
    secrets: inherit
