name: Run CrossDC functional tests on ROSA cluster

on:
  workflow_call:
    inputs:
      clusterPrefix:
        description: 'The prefix used when creating the Cross DC clusters'
        type: string
      activeActive:
        description: 'Must be true when testing against an Active/Active Keycloak deployment'
        type: boolean
        default: false

  workflow_dispatch:
    inputs:
      clusterPrefix:
        description: 'The prefix used when creating the Cross DC clusters'
        type: string
      activeActive:
        description: 'Must be true when testing against an Active/Active Keycloak deployment'
        type: boolean
        default: false
      externalInfinispanEnabled:
        description: 'True if the deployment uses the External Infinispan feature'
        type: boolean
        default: false

concurrency:
  # Only run once for the latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT: runner-keycloak

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Cache Maven Wrapper
        uses: actions/cache@v4
        with:
          path: |
            .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-wrapper-

      - name: Setup ROSA CLI
        uses: ./.github/actions/rosa-cli-setup
        with:
          aws-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-default-region: ${{ vars.AWS_DEFAULT_REGION }}
          rosa-token: ${{ secrets.ROSA_TOKEN }}

      - name: Login to OpenShift cluster A
        uses: ./.github/actions/oc-keycloak-login
        with:
          clusterName: ${{ inputs.clusterPrefix }}-a

      - name: Get DC1 Context
        shell: bash
        run: echo "KUBERNETES_1_CONTEXT=$(kubectl config current-context)" >> "$GITHUB_ENV"

      - name: Login to OpenShift cluster B
        uses: ./.github/actions/oc-keycloak-login
        with:
          clusterName: ${{ inputs.clusterPrefix }}-b

      - name: Get DC2 Context
        shell: bash
        run: echo "KUBERNETES_2_CONTEXT=$(kubectl config current-context)" >> "$GITHUB_ENV"

      - name: Run CrossDC functional tests
        run: ./provision/rosa-cross-dc/keycloak-benchmark-crossdc-tests/run-crossdc-tests.sh
        env:
          ACTIVE_ACTIVE: ${{ inputs.activeActive }}
          DEPLOYMENT_NAMESPACE: ${{ env.PROJECT }}
          SKIP_EMBEDDED_CACHES: ${{ inputs.externalInfinispanEnabled }}
