name: ROSA Cluster - Scaling Benchmark on Schedule

on:
  schedule:
    - cron: '0 7 * * 1-5' # Runs At 07:00 UTC on every day-of-week from Monday through Friday.

jobs:

  checkout:
    name: ROSA Scheduled Scaling Benchmark Run
    runs-on: ubuntu-latest
    steps:
      - name: Run ROSA Scaling Benchmark
        run: |
          gh workflow run -R keycloak/keycloak-benchmark rosa-scaling-benchmark.yml -f clusterName=gh-keycloak-a -f skipCreateDeployment=true -f skipDeleteProject=true
        if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
