= Configuration of database connection pools
:navtitle: Database connection pools
:description: This describes the reasoning behind configuring database connection pools for {keycloak}.

{description}

== Audience

Read this page to understand considerations and best practices on how to configure database connection pools for {keycloak}.
For a configuration where this is applied, visit xref:running/keycloak-deployment.adoc[].

== Concepts

Creating new database connections is expensive as it takes time.
Creating them when a request arrives will delay the response, so it is good to have them created before the request arrives.
It can also contribute to a https://en.wikipedia.org/wiki/Cache_stampede[stampede effect] where creating a lot of connections in a short time makes things worse as it slows down the system and blocks threads.
Closing a connection also invalidates all server side statements caching for that connection.

include::partial$configure-db-connection-pool-best-practices.adoc[]

